### ISSUE TITLE
Extension Leaflet Geocodage : traduction des champs du service en français 

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#10]
Dans le popup d'une parcelle, les noms des champs sont en "anglais".

**Comment by gcebelieu** [comment]
Pour l'instant on a juste retranscrit les champs (en anglais) retournés par le service.
On pourra les traduire pour le rendu dans la popup.

**Comment by lowzonenose** [comment]
Plus d'actualité..., les valeurs des champs sont concaténées, et les champs n'apparaissent plus...
