### ISSUE TITLE
Error in GeoportalAttribution when adding a ol.layer.Group

### ISSUE THREAD

**Issue by thhomas** [IGNF/geoportal-extensions#102]
In GeoportalAttribution, when updating attributions, a call to getSource function is made on map.getLayers(). When a layer is an ol.layer.Group, getSource does not exists and generates an error.

**Comment by gcebelieu** [comment]
@lboulanger pourras-tu y jeter un oeil ?

**Comment by lboulanger** [comment]
Indeed, layers of type ol.layer.Group were not managed. It should  be solved by [this commit](https://github.com/IGNF/geoportal-extensions/commit/e3efb9d9623cb60b945797ea0fe2bb20e3efcb59).
