### ISSUE TITLE
Extension OL3 :  embarquer la mesure de distance et de surface dans l'outil de dessin

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-extensions#103]
EVOL possible issue du ticket #84 
> Les mesures effectuées par les outils proposés ne sont pas exportables, seuls les outils de dessins permettent de sauvegarder une couche comme vous l'avez bien remarqué.
> Pour permettre cela, il faudrait à mon avis faire évoluer les outils de dessin pour qu'ils embarquent la mesure de distance et de surface lorsqu'on trace une ligne ou un polygone et l'affichent comme texte par défaut dans la la popup à la fin du tracé. C'est à étudier.

**Comment by F3L1X79** [comment]
Bonjour,
Désolé de demander ça comme ça, mais j'hésitais à me lancer dans des développements persos pour résoudre cette évolution de fonctionnalité.
J'aurais souhaité savoir si vous aviez déjà démarré quelque chose de votre côté avant de me lancer ?
Par avance merci pour votre réponse.

**Comment by gcebelieu** [comment]
Bonjour,
pour l'instant nous n'avons rien entamé sur le sujet qui reste encore à cadrer.
Vous souhaitiez faire des développements dans l'optique d'une contribution aux outils de l'extension Géoportail ou dans un composant à part ?

**Comment by F3L1X79** [comment]
Au départ l'un ou l'autre indifféremment, mais j'ai finalement opté pour la création d'un module à part qui calcule les longueurs des annotations que j'enregistre manuellement, provenant de la couche dessin. Je pourrais poster le code si un autre utilisateur est intéressé, mais je sais que votre équipe n'en aura pas besoin. (C'est trop long et compliqué pour mes besoins actuels de partir sur une solution plus générique pour les outils géoportails).

**Comment by gcebelieu** [comment]
OK. Dans tous les cas, nous porterons l'information sur cette issue lorsque nous entamerons ce chantier.

**Comment by lowzonenose** [comment]
Mesures  insérées dans l'outil de dessin. Pour plus d'informations cf. PR #189.
