### ISSUE TITLE
Création d'un processus de build d'extensions "mixtes"

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#105]
Lorsqu'on veut utiliser deux extensions à la fois (exemple : extensions ol3 + vg) , on charge plusieurs fois du code qui pourrait être mis en commun : bibliothèque d'accès et proj4 notamment.

Il faudrait pouvoir rajouter une entrée dans le gulpfile permettant de créer une extension "mixte" qui factoriserait ainsi le code commun.

Idéalement cette entrée serait paramétrable selon le type d'extension que l'on souhaite regrouper. Exemple d'utilisation :

> gulp build --ol3 --vg

**Comment by lowzonenose** [comment]
(utilisation interne)
Le mode mixte permet de regrouper différente extension (Openlayers et 3D) au sein d'un même 'bundle'.
_Execution_
`gulp --ol3 --vg --mix`
_Publication_ (dist/mix)
`gulp publish --ol3 --vg --mix`
