### ISSUE TITLE
ol.control.SearchEngine : postalcode autocompletion returns null coordinates [0,0]

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#107]
Si on saisit un code postal dans la barre de recherche du composant : les résultats d'autocomplétion ont tous des positions dont les coordonnées sont 0,0 (on se retrouve au large de l'Afrique). 
C'est un défaut du service, qu'il faut pouvoir contourner.

**Comment by lboulanger** [comment]
Correctif : avant d'afficher les résultats de l'autocompletion, on vérifie leurs coordonnées. Si elles sont nulles, on lance une requête de géocodage avec le texte renvoyé (par exemple "75000 Paris"), pour récupérer des coordonnées correctes. On affiche ensuite le résultat corrigé dans la liste des résultats.

**Comment by lboulanger** [comment]
Un autre souci apparaît (remontée utilisateur) : 
Lors de la saisie d'un code postal, le résultat s'affiche bien (après une requête de géocodage), mais une requête de géocodage est ensuite relancée à chaque fois que l'on saisit des espaces (ou encore après des actions comme appuyer sur "shift", "page up", "ctrl", et que le texte dans la barre de recherche ne contient qu'un code postal (pas d'autres caractères texte). Cela génère des doublons : 
![doublons-searchengine](https://user-images.githubusercontent.com/17139628/29676725-1b9fa462-88f9-11e7-8502-941bea883cc3.png)

Il faut améliorer le correctif ci-dessus, pour ne pas afficher ces doublons.

**Comment by lboulanger** [comment]
Correction apportée (https://github.com/IGNF/geoportal-extensions/commit/d2905634750f9d500f401c5e755ab6f13601db29) : la liste est regénérée à chaque action du clavier (exactement comme pour les autres recherches d'autocomplétion). 
Seul léger effet de bord (uniquement pour la recherche par code postal) : comme les requêtes de géocodage sont à peine moins rapides que celles d'autocomplétion, elles n'arrivent pas toujours exactement dans le même ordre, qui peut donc varier lorsqu'on a plusieurs communes pour un même code postal. (ex. 01100). A voir si c'est vraiment gênant.

Bonus : correction apportée aussi pour Leaflet (récupération des coordonnées lorsqu'elles sont nulles (code postal)) : https://github.com/IGNF/geoportal-extensions/commit/d563416bb8d206a5d8a5e98b2315f051709b3c69

**Comment by lowzonenose** [comment]
BUG 

> Résolu...

OPTIMISATION POSSIBLE (enhancement)

> A sujet des résultats du *geocodage* qui ne génèrent pas le même ordre d'affichage (plusieurs communes pour un même code postal) est quelque chose de difficilement *optimisable* en l'état (ex. synchronisation des requêtes de geocodage, stocker la recherche par code postale, ...).

**Comment by gcebelieu** [comment]
Le problème qui a motivé cette issue étant corrigé par la résolution de #151 je propose de la fermer.
Pour la partie "enhancement", nous créerons une nouvelle issue dédiée si le besoin s'en fait sentir.
