### ISSUE TITLE
[Safari][OL3] Profil altimétrique

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#108]
Dans les outils de mesure, le calcul d'un profil altimétrique ne fonctionne pas sous Safari Mac (Ok pour Chrome et Firefox).

**Comment by lowzonenose** [comment]
Peux tu nous fournir plus d'informations (version OS, capture écran, messages consoles,...)? 
Merci

**Comment by F3L1X79** [comment]
Oui sur le fiddle habituel : 
http://jsfiddle.net/krj9yp6f/7/embedded/result,js,html/

Il suffit de déplier les outils de mesure, en haut à gauche, sélectionner le 4ème en partant du haut (Calculer un profil altimétrique) et tirer un trait au milieu de la carte.
=> On constate que le graphe du profil altimétrique qui apparait est "plat" sur Safari uniquement.
=> Pas de messages d'erreur apparant dans la console.
=> Version de Safari : Version 10.0.1 (11602.2.14.0.7) - sur El Capitan.

**Comment by lowzonenose** [comment]
@F3L1X79, peux tu valider le profil alti sous Safari ?
Merci

**Comment by F3L1X79** [comment]
J'ai toujours le problème sur ce fiddle.

**Comment by lowzonenose** [comment]
Oups, le build d'intégration continue du projet vient de se terminer à l'instant !
Désolé, peux tu (re)valider sur le fiddle ?  
Merci

**Comment by F3L1X79** [comment]
Toujours KO de mon côté.

**Comment by iamvdo** [comment]
Hello,
J'ai eu l'info par Cédric.
C'est un problème connu de Flexbox. Bien que la hauteur de `.profile-box` soit `flex: 1`, elle n'est pas automatiquement utilisée par son enfant en 100%. Il suffit donc de lui forcer `height: 100%`. Le problème supplémentaire ici, c'est que `.profile-box` ne doit pas être de 100%, donc il faudrait fixer la hauteur de `.profil-x-horizontal`, et enlever cette hauteur à `.profile-box`, par exemple:

```css
.profil-x-horizontal {
  height: 15px
}
.profile-box {
  height: calc(100% - 15px)
}
```

Mais je suis d'accord que c'est dommage.
Vincent

**Comment by lowzonenose** [comment]
Merci les experts CSS sous Safari !
@F3L1X79, tu peux de nouveau tester la modification CSS sur l'extension ElevationPath sous Safari.
