### ISSUE TITLE
Extension OL3: Ajout d'un titre par défaut à la couche layerSwitcher après l'ajout d'une Annotation

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#109]
Bonjour,
A l'ajout d'une nouvelle annotation via la couche Dessin, le nom de la couche ajoutée (du dernier layer de dessin) dans le layerSwitcher prend automatiquement le nom d'un ID (un numéro).

Ex : j'ai déjà 3 couches dans mon layerSwitcher; je veux rajouter un point, le nom de la nouvelle couche Dessin ajoutée se nommera automatiquement '4'.

Est-ce possible de la renommer automatiquement à la création par un nom spécifique via un 'trigger' OpenLayer, ou un élément de configuration côté API IGN ?

Merci d'avance pour votre réponse.

**Comment by lboulanger** [comment]
Bonjour,

_1. écouteur d'événement à l'ajout d'une couche à la carte_
En effet, vous pouvez utiliser l'écouteur d'événements d'OpenLayers sur les couches de la carte : map.getLayers() retourne une ol.Collection dont on peut écouter les ajouts d'éléments (de couche dans notre cas) (http://openlayers.org/en/latest/apidoc/ol.Collection.html#on).

_2. n'intercepter que les couches de croquis_
Pour identifier s'il s'agit d'une couche de croquis, il suffit de regarder la valeur du paramètre "gpResultLayerId" de la couche, qui doit valoir "drawing" s'il s'agit d'une couche créée par le widget de création de croquis. (attention ce paramètre n'existe pas pour les couches natives OpenLayers, c'est un ajout de l'extension Géoportail)

_3. modifier le titre dans le layerSwitcher_
Il s'agit cette fois de la méthode addLayer du widget LayerSwitcher (http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.LayerSwitcher.html#addLayer), qui prend en paramètres 1. la couche dont on veut modifier la conf, et 2. un objet avec la conf à ajouter dans le layerSwitcher.

Par exemple le code suivant permet d'ajouter un titre ("Croquis" et une description ("Mon croquis") aux couches de croquis ajoutées par le widget :

```
map.getLayers().on("add", function(e) {
    var addedLayer = e.element;
    if ( addedLayer.gpResultLayerId && addedLayer.gpResultLayerId === "drawing" ) {
        layerSwitcher.addLayer(
            addedLayer,
            {
                title : "Croquis",
                description : "Mon croquis"
            }
        );
    }
})
```

**Comment by lboulanger** [comment]
Une évolution qu'on pourrait mettre en place dans l'outil de Croquis : ajouter systématiquement un titre par défaut quand un layerSwitcher est présent dans la carte, comme c'est déjà le cas pour les calculs d'itinéraires, d'isochrones, de recherche inverse, ...
(Ce titre pourrait bien sûr être surchargé par l'utilisateur comme présenté ci-dessus)
Je laisse ouvert le ticket pour cette évolution à mettre en place.

**Comment by F3L1X79** [comment]
Honnêtement la réponse me sauve complètement et ma va très bien, vous pouvez clore ce ticket sans problème si cette évolution et un peu chiante à mettre en place pour vous.
Merci encore pour toutes les informations !!

**Comment by lboulanger** [comment]
Merci pour votre retour !
On garde quand même l'évolution ouverte (aussi dans un souci d'homogénéité avec les autres widgets), mais avec une priorité faible (puisque l'utilisateur peut facilement le faire lui-même si besoin).

**Comment by EPINRAP** [comment]
hello la compagnie
bien heureux de trouver ce code pour identifier le layer "Drawing" modifiable.
euh 

> avec une priorité faible (puisque l'utilisateur peut facilement le faire lui-même si besoin).
par utilisateur j'entends celui qui utilise l'interface web, qui lui ne touche pas au code. Et donc ce facile n'est pas pour lui. Même le concepteur que je suis en apprends tous les jours et je ne suis pas encore capable de rendre le titre du layer éditable, ce qui au final serait souhaitable. Donc pas facile pour moi non plus.
