### ISSUE TITLE
L.geoportalControl.ReverseGeocode : recherche lieudit, centrage

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#11]
Sur un lieu éloigné des points Département/Région, la carte est centrée sur l'emprise de lieu/département/région, ce qui est inutilisable.

**Comment by gcebelieu** [comment]
C'est un comportement du service qui retourne systématiquement la commune, le département et la région lorsqu'on fait du Géocodage inverse sur les toponymes.
Pour l'instant le widget centre la visu sur tous les résultats.
A voir si on ne tient pas compte de ces résultats spécifiques : c'est à réfléchir.
