### ISSUE TITLE
Extension OL3: Evénement IGN disponible après l'ajout d'une annotation ?

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#111]
Bonjour,

Je souhaiterai savoir s'il existe un trigger disponible après l'ajout d'une annotation (couche dessin) dans votre API ?

Mon cas d'usage : j'aurais besoin de sauvegarder chaque annotation (feature) dans un objet spécifique afin de le stocker, et ce, dès qu'une d'elle vient d'être ajoutée.

Mon code actuel : 
```
_self = this;
map.getInteractions().on("add", function(e) {
                                    var interaction = e.element;
                                    if (interaction && interaction instanceof ol.interaction.Draw) {
                                        if (interaction.getProperties() && interaction.getProperties().source && interaction.getProperties().source.layer) {
                                            if (interaction.getProperties().source.layer.gpLayerId) {
                                                interaction.getProperties().source.layer.userId = userId;
                                                interaction.on("drawend", function(d) {
                                                    setTimeout(function() {
                                                        _self.saveAnnotations();
                                                    }, 0);
                                                });
                                            }
                                        }
                                    }
                                });
```

Ce code fonctionne très bien, seul bémol : La popup qui apparait automatiquement après l'ajout d'une annotation et qui permet d'ajouter une légende ne sera jamais sauvegardée.
Pour pallier à ça, serait-il possible : 
   - de permettre aux développeurs de la désactiver ?
   - ou sinon, obtenir un événément après le click du bouton "Enregistrer" de la popup qui apparait ?

Un grand merci d'avance pour vos réponses, et pour toute l'aide que vous avez pu m'apporter jusqu'ici !

**Comment by gcebelieu** [comment]
Bonjour,

Si je comprends bien ce que vous souhaitez faire, ne vaudrait-il mieux pas s'abonner à l'événement d'ajout ou de suppression des features sur le ol.source.Vector associé à l'outil de dessin pour déclencher votre traitement ? Cela permettrait de ne pas écraser les événements associés aux interactions existantes de l'outil de dessin.

**Comment by F3L1X79** [comment]
Bonjour,

Merci pour votre réponse; si c'est bien cela qu'il faudrait faire ; mais je ne pensais même pas que c'était possible donc j'avais temporairement abandonné l'idée. (J'ai essayé plusieurs bout de code sans succès, n'étant pas un expert avec l'API OL3).

En attendant j'ai simplement masqué la popup en question:
```
.ol-overlay-container .gp-label-div {
    display: none !important;
}
```

Si j'arrive à faire fonctionner ce que vous préconisez, je viendrais le poster ici.
