### ISSUE TITLE
Attribut "data-key" non reconnu ?

### ISSUE THREAD

**Issue by tflorac** [IGNF/geoportal-extensions#113]
Bonjour,

Je tente de charger l'extension Géoportail pour Leaflet en utilisant l'attribut "data-key" sur ma balise "<script>" pour indiquer ma clé d'accès à l'API.

Mais lors de la création d'une couche, une erreur est affichée dans la console du navigateur :

```
var ignf = L.geoportalLayer.WMTS({
	layer: 'GEOGRAPHICALGRIDSYSTEMS.MAPS'
})
ignf.addTo(map);
```
```
PARAM_MISSING : apiKey !
WARNING PARAM_MISSING : parameter 'apiKey' is mandatory if the contract key configuration has not been loaded !
```

Je n'ai pas cette erreur si j'utilise l'attribut "apiKey" lors de la création de la couche...

**Comment by lboulanger** [comment]
Bonjour,

Mis à part les messages d'informations qui s'affichent en console, est-ce que votre couche s'affiche bien ou pas du tout ?
Si elle ne s'affiche pas, une première solution est de vérifier que votre code ne s'exécute bien qu'au chargement complet de la page et de tous ses scripts (window.onload), ce qui permet de s'assurer que les informations de configuration de votre clé (autoconf) ont bien été récupérées. Par exemple :

```
window.onload = function () {
	var ignf = L.geoportalLayer.WMTS({
		layer: 'GEOGRAPHICALGRIDSYSTEMS.MAPS'
	})
	ignf.addTo(map);
}
```

**Comment by tflorac** [comment]
Non, la couche ne s'affiche pas.
Le code s'exécute bien au chargement complet de la page via une instruction jQuery "$(document).ready(...)".
En ajoutant simplement la clé d'API ça fonctionne normalement :
```
	var ignf = L.geoportalLayer.WMTS({
		layer: 'GEOGRAPHICALGRIDSYSTEMS.MAPS',
		apiKey: 'xxxx'
	})
	ignf.addTo(map);
```

**Comment by lboulanger** [comment]
Bonjour,

"$(document).ready(...)" permet seulement de s'assurer que le document DOM est prêt pour l'exécution du code JavaScript, mais il faut utiliser "$(window).on("load",function (){...})" pour s'assurer que l'ensemble des scripts sont bien chargés (et donc le chargement de l'autoconf pour vérifier les droits de votre clé).

Ça devrait mieux fonctionner, tenez moi au courant.

Laurane

**Comment by tflorac** [comment]
Effectivement, tout semble fonctionner normalement lorsque l'on passe par l'événement "load" de la fenêtre...!!
