### ISSUE TITLE
Extension leaflet : formulation et orthographe du message d'erreur missing apiKey

### ISSUE THREAD

**Issue by sheiden** [IGNF/geoportal-extensions#118]
"WARNING : parameter 'apiKey' has not been parametered, and the contract key configuration has not been loaded, so impossible to check yours rights !  GpPluginLeaflet.js:144:28432"
->
"WARNING: the 'apiKey' parameter is missing, and the contract key configuration has not been loaded, so impossible to check your rights!  GpPluginLeaflet.js:144:28432"

**Comment by gcebelieu** [comment]
https://github.com/IGNF/geoportal-extensions/commit/bacc63eda4da1b701350ecc1ae151ff40b82e97b

Merci :)
