### ISSUE TITLE
Compilation sous windows

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#119]
Il s'agit de tester la compilation sous environnement Windows ... et la faire fonctionner, en documentant les prérequis.

**Comment by lowzonenose** [comment]
_Gestion des fins de lignes sous Windows :_ 
```
git config core.autocrlf false
git rm --cached -r .
git reset --hard
```

**Comment by lowzonenose** [comment]
Procédure identique que celle pour la compilation sous Windows de l'API d’accès aux Services, à l'exception de l’exécution des exemples : 

> ## Exécution des exemples Leaflet
> 
> **ouvrir une console**
> 
>     gulp server --leaflet
> 
> Le navigateur s'ouvre sur la page des exemples sur l'URL suivante :
> http://localhost:9001/samples/index-leaflet.html
> 
> ## Exécution des exemples OpenLayers
> 
> **ouvrir une console**
> 
>     gulp server --ol3
> 
> Le navigateur s'ouvre sur la page des exemples sur l'URL suivante :
> http://localhost:9001/samples/index-ol3.html
> 
> ## Exécution des tests
> 
> Pas de taches d’exécution des tests unitaires en mode browser (uniquement en mode console)
