### ISSUE TITLE
L.geoportalControl.ReverseGeocode : recherche lieudit, pas de lieudit trouvé

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#12]
En cliquant à proximité d'un lieudit, la recherche ne trouve pas ce lieudit. Il faut taper précisement sur le lieudit.

**Comment by lboulanger** [comment]
Bonjour,

Pourriez-vous nous donner un exemple plus concret du problème que vous avez rencontré ?
Cela pourrait nous permettre d'en identifier l'origine.

**Comment by mgageo** [comment]
Comme le marqueur bleu disparait (ce n'est pas une bonne idée), il est difficile de faire un exemple.
Sur cette demande,aucun lieudit trouvé
iiiiii
![ignf_apiv3](https://cloud.githubusercontent.com/assets/2681495/16011199/bb896f6c-3184-11e6-8b72-5396842f7a34.jpg)
une autre requête sans réponse
	
<?xml version="1.0" encoding="UTF-8"?>
<xls:XLS version="1.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xls="http://www.opengis.net/xls" xmlns:gml
="http://www.opengis.net/gml" 
xsi:schemaLocation="http://www.opengis.net/xls http://schemas.opengis.net/ols/1.2/olsAll.xsd">
<xls:RequestHeader srsName="EPSG:4326"/>
<xls:Request maximumResponses="25" methodName="ReverseGeocodeRequest" requestID="9cb19034-9d8d-4c2a-a506-096515958001"
 version="1.2"><xls:ReverseGeocodeRequest returnFreeForm="false"><xls:Position><gml:Point xmlns:gml="http
://www.opengis.net/gml"><gml:pos>48.13447544771421 -1.5008568763732912</gml:pos></gml:Point></xls:Position
><xls:ReverseGeocodePreference>PositionOfInterest</xls:ReverseGeocodePreference></xls:ReverseGeocodeRequest
></xls:Request>
</xls:XLS>

**Comment by gcebelieu** [comment]
C'est une limitation du service qui ratisse très étroit autour du point de recherche.
Au niveau des extensions on ne fait que reflèter le comportement du service.
Ce sujet a été transmis à l'équipe gestionnaire du service de géocodage inverse.
