### ISSUE TITLE
Remplacer les références à OL3 en OL

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#129]
Parce qu'on en est depuis quelques temps à OL4 et que l'extension Géoportail est compatible avec OL4.

**Comment by lowzonenose** [comment]
Pour être cohérent, il faut aussi supprimer toutes les références à OL3 dans la documentation.
Le remplacement des références risque de casser des liens vers...
* Téléchargement 
Ex. https://github.com/IGNF/geoportal-extensions/releases/download/ol3-0.12.0/GpOpenLayers.zip
* JSDoc 
Ex. http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.layer.GeoportalWMTS.html
* Geoservices
Ex. http://ignf.github.io/evolution-apigeoportail/ol3/ol3-autoconf.html


Autre souci, le paramètre des requêtes WMTS et WMS "gp-ol3-ex" est à modifier..., mais ça risque de fausser les statistiques API (modification à prévoir sur la configuration ElasticSearch)

**Comment by lowzonenose** [comment]
Remplacer les références à OL3 en : 
* OL : Les bundles, Ex. *GpPluginOL.js*
* OpenLayers :  Les répertoires internes au projet, Ex. *src/Openlayers/* ou *samples/Openlayers/*
* openlayers : Les répertoires, Ex. *dist/openlayers/* ou *lib/openlayers/*

**Comment by lowzonenose** [comment]
Impact direct sur le projet SDK !
Il faut modifier les références aux plugins OpenLayers dans le répertoire *lib/external/geoportail* (__remarque__ : répertoire à renommer en *lib/geoportal-extensions/*)

On en profite aussi pour supprimer les références OL3 sur le projet SDK : 
* renommer les répertoires *res/ol3*, *src/ol3*, *samples/ol3*, ...
* la jsdoc et la documentation 
* les exemples
* la classe OL3 !!!
