### ISSUE TITLE
Support IE9 envisageable pour OL3 ?

### ISSUE THREAD

**Issue by sylvainpolletvillard** [IGNF/geoportal-extensions#13]
Bonjour,

Je viens de remarquer l'annonce des navigateurs supportés dans readme-ol3.md, qui m'a un peu surpris car je m'attendais à avoir le même périmètre de support qu'Open Layers 3. L'exclusion d'IE9 est assez contraignante pour notre projet, j'ai donc comme questions:
- est-ce que certaines fonctionnalités de l'extension OL3 excluent techniquement IE9 sans fallback possible ?
- si non, envisagez-vous d'ajouter IE9 au périmètre de support ?
- si non, pouvons-nous nous en charger et soumettre une pull request ? et avez-vous une idée de la charge de travail que cela représenterait ?

Merci d'avance

**Comment by gcebelieu** [comment]
Bonjour,

le non support d'IE9 est essentiellement du à l'utilisation de mécanismes flexbox dans les CSS de l'extension (cf. http://caniuse.com/#feat=flexbox). Cela est donc à priori gênant pour l'affichage des widgets, mais pas pour le fonctionnel pur de l'extension. Nous n'avons à priori pas prévu dans nos actions d'étendre ce support à IE9, mais s'il l'est c'est bien sûr encore mieux.

Vous devriez pouvoir vous en sortir en surchargeant les CSS de l'extension avec des mécanismes plus traditionnels supportés par IE9.  En termes de charge de travail, cela va donc dépendre de vos compétences en CSS pur. 

Dans tous les cas si vous êtes partant pour explorer cette voie, votre contribution à ce projet sera la bienvenue :)

**Comment by sylvainpolletvillard** [comment]
S'il s'agit juste des flexbox, ça ne devrait pas poser de problème :)
Merci pour les infos, je ferme ce ticket et reviendrais peut-être avec une PR.
