### ISSUE TITLE
Affichage des coordonnées géographiques (MousePosition) : échanger latitude et longitude

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#139]
Actuellement, dans l'outil d'affichage des coordonnées de la souris, les coordonnées géographiques sont présentées sous la forme Latitude puis Longitude : 
![coordslatlon](https://user-images.githubusercontent.com/17139628/28682407-1b6a3cee-72fd-11e7-9338-fe132650e732.png)

Il serait peut-être plus clair de les présenter sous la forme Longitude puis Latitude.

Bonus : remplacer le point par une virgule ?

**Comment by elias75015** [comment]
La norme internationale spécifie Latitude/Longitude : https://en.wikipedia.org/wiki/ISO_6709#Order,_sign,_and_units
Le RGF93 spécifie du Longitude/Latitude...

Quel système de référence pour nos outils de mesure ? Reporté en interne
