### ISSUE TITLE
Extension Leaflet Layer : Provide custom serviceUrl

### ISSUE THREAD

**Issue by Brictarus** [IGNF/geoportal-extensions#142]
Hello,

In the file `Leaflet/Layers/Layers.js` we've found : 

```javascript
serviceUrl : "http://localhost?no-rights-found-for=[{layer}]"
```
This code calls an url that obviously doesn't exist... It would be really helpful to be able to overload this `serviceUrl` variable when creating the layer instead of having that constant value.

For example, on my current project, we want to use an Apache web server as a proxy between the client application (embedding the leaflet stuff and this plugin) and the IGN API. But we can't make it work as we cannot modify the `serviceUrl` value.

**Comment by lowzonenose** [comment]
It's not a constant value, you can overload it...

**Comment by Brictarus** [comment]
I assume you're talking about the `serverUrl` in the `Common/Utils/AutoLoadConfig.js` file. But this option apparently does not allow to modify the host used in the `GetTile` requests, which remain to *wxs.ign.fr*.

I'm missing something ?

**Comment by lowzonenose** [comment]
I'm sorry for the late response...
You can modify the url (WMS and WMTS service): 

```
var wms = L.geoportalLayer.WMS({
        layer : "ORTHOIMAGERY.ORTHOPHOTOS"
      },{
        attribution : "IGN",
        opacity : 0.5,
        minZoom : 5,
        maxZoom : 8,
        styles : "normal",
        format : "image/png",
        version : "1.3.0"
      });

wms._url = "http://myproxy.fake.fr?url=http%3A%2F%2Fwxs.ign.fr%2Fjhyvi0fgmnuxvfv0zjzorvdn%2Fgeoportail%2Fr%2Fwms";

var map  = L.map('map', {
        zoom : 6,
        center : L.latLng(48, 2)
 });

wms.addTo(map);
```

**Comment by Brictarus** [comment]
Thank you for this answer. It works. But modifying a "private" attribute don't look like a reliable long term solution. Do you plan to make a feature (eg. add an option in the options object in geoportalLayer.WMS/WMTS constructor) for this ?

**Comment by gcebelieu** [comment]
Hi,
it seems that the setter already exists (thanks to Leaflet). Did you try : 
```

var wms = L.geoportalLayer.WMS({
        layer : "ORTHOIMAGERY.ORTHOPHOTOS"
      }).setUrl("http://myproxy.fake.fr?url=http%3A%2F%2Fwxs.ign.fr%2Fjhyvi0fgmnuxvfv0zjzorvdn%2Fgeoportail%2Fr%2Fwms") ;

var map  = L.map('map', {
        zoom : 6,
        center : L.latLng(48, 2)
 });
wms.addTo(map);
```
