### ISSUE TITLE
drawing tools conflicts with openlayers popups 

### ISSUE THREAD

**Issue by geomoes** [IGNF/geoportal-extensions#143]
I want to use the GpPluginOl3.js plugin together with popups, but I cannot use them together.
The drawing tools still allow me to draw points, lines, polygons and even to edit them, but I cannot change the style, edit text or delete features. When I'm removing the popups, everything works fine.
I've tryed several libraries like popupoverlay.js de J-M.Viglino ([url]https://github.com/Viglino[/url]) and ol-popup de Matt Walker ([url]https://github.com/walkermatt[/url]). Even a simple popup with bootstrap and jQuery leads to the discribed malfunction.
Here the relevant parts of the code I'm using:

    var map = new ol.Map({
        target: 'map',
        view: view,
        controls: ol.control.defaults().extend([
            new ol.control.Zoom(),
            new ol.control.FullScreen(),
            new ol.control.ZoomSlider(),
            new ol.control.LayerSwitcher(),
            new ol.control.OverviewMap(),
            new ol.control.ScaleLine(),
            new ol.control.Drawing(),
            new ol.control.LayerImport(),
            new ol.control.MeasureArea(),
            new ol.control.MeasureLength(),       
        ]),
        layers: [baselayers, toplayers],
        interactions: ol.interaction.defaults().extend([
            new ol.interaction.Select({
                layers: [baselayers, toplayers]
            })
        ])
    });

    var popup = new ol.Overlay.Popup({
                        popupClass: "default",
			closeBox: true,
			positioning: 'auto',
			autoPan: true,
			autoPanAnimation: { duration: 250 }
			});
    
    map.addOverlay(popup);
    
    map.on('click', function(evt) {
        var feature = map.forEachFeatureAtPixel(evt.pixel,
            function(feature, layer) {
                return feature;
            });
        var popupContent = map.forEachLayerAtPixel(evt.pixel,
            function(layer) {
                return layer.get('content');
            });
        if (feature) {
            popup.setPosition(evt.coordinate);
            var atts = feature.getProperties();
            for (var prop in atts) {
                var re = new RegExp("{" + prop + "}", "g");
                popupContent = popupContent.replace(re, atts[prop]);
            }
            popup.show(evt.coordinate,popupContent);
        } else {
            popup.hide();
        }
    });

**Comment by lowzonenose** [comment]
Can you do a demo with jsfiddle ?

**Comment by lowzonenose** [comment]
I use the ol-popup de Matt Walker ([url]https://github.com/walkermatt[/url]) in my samples, and i haven't any problem...

```
                var map;
                window.onload = function() {
                    
                    map = new ol.Map({
                        target : "map",
                        layers : [new ol.layer.GeoportalWMTS({
                            layer: "GEOGRAPHICALGRIDSYSTEMS.MAPS",
                        })],
                        view : new ol.View({
                            center : [288074.8449901076, 6247982.515792289],
                            zoom : 8
                        })
                    });

                    var drawing = new ol.control.Drawing({
                        collapsed : false,
                    });
                    map.addControl(drawing);

                    var popup = new ol.Overlay.Popup();
                    map.addOverlay(popup);

                    map.on("click", function(evt) {

                      popup.hide();
                      popup.setOffset([0, 0]);

                      // Attempt to find a feature in one of the visible vector layers
                      var feature = map.forEachFeatureAtPixel(evt.pixel, function(feature, layer) {
                          return feature;
                      });

                      if (feature) {

                          var coord = feature.getGeometry().getCoordinates();
                          var props = feature.getProperties();
                          var content = props["description"] || props["name"];
                          // Offset the popup so it points at the middle of the marker not the tip
                          popup.setOffset([0, -22]);
                          popup.show(coord, content);

                      }
                    });
                };
```

**Comment by lowzonenose** [comment]
To retrieve the contents of the popup, you can do it : 
```
var props = feature.getProperties();
var content = props["description"] || props["name"];
```
In your code, you can delete and replace this section : 
```
 var popupContent = map.forEachLayerAtPixel(evt.pixel,
        function(layer) {
            return layer.get('content');
        });
```

**Comment by geomoes** [comment]
For me that doesn't work, since the popups use different templates for each layer. My code needs to fetch the template first, and then replace the placeholders with the correct values.
```
var popup = new ol.Overlay.Popup();
map.addOverlay(popup);

    map.on('click', function(evt) {
        var feature = map.forEachFeatureAtPixel(evt.pixel,
            function(feature, layer) {
                return feature; // checks if feature exists on layer 
            });
        var popupContent = map.forEachLayerAtPixel(evt.pixel,
            function(layer) {     
                return layer.get('content'); // template-string of layer
            });
        if (feature) {
            popup.setPosition(evt.coordinate);
            var atts = feature.getProperties(); // object
            for (var prop in atts) {
                var re = new RegExp("{" + prop + "}", "g");
                popupContent = popupContent.replace(re, atts[prop]); // replace {placeholder} with values of placeholder
            }
            popup.show(evt.coordinate,popupContent);
        }        
        else {
            popup.hide();
        }
    }); 
```
It seems as if my code is interacting in a strange way with the code of the drawing tools.
I've observed the following three cases:
1. clicking on feature => shows popup with correct values of my placeholders
2. clicking on new drawn polygon => nothing happens when trying to change style, edit text or delete this polygon
3. clicking on a new drawn polgon, that overlaps with an existing feature => popup shows up, but placeholders don't get replaced with values AND the popup for styling, editing shows up and new drawn polygons can even be deleted.

I'll try to install a jsfiddle to demonstrate this live, but maybe You have already an idea where the problem could lie.
