### ISSUE TITLE
Calcul d'Isochrone, pointeur qui ne se place pas au bon endroit

### ISSUE THREAD

**Issue by MagNess76** [IGNF/geoportal-extensions#144]
Bonjour,

Je ne sais pas si c'est un bug ou si c'est un problème de configuration mais à certains endroits, quand on veut placer le pointeur, il se déporte sur un autre endroit. Cela semble lié à une adresse, le problème ce que pour mon projet de calcul d'isochrone, il faut absolument que le pointeur se mette à l'emplacement pointé.
Ex: 
![image](https://user-images.githubusercontent.com/31239375/29557046-2735e372-8728-11e7-8025-5ecc95478624.png)

J'ai pointé au niveau de la croix rouge.
L'adresse retournée : 11 bd ferdinand de lesseps, 76000 Rouen

Avez-vous une solution à me proposer ?

Merci beaucoup de votre aide.

**Comment by lowzonenose** [comment]
Appuyer sur la touche CTRL + déplacer le point.

**Comment by lowzonenose** [comment]
On peut aussi désactiver la recherche inverse : 
`disableReverse : true`
