### ISSUE TITLE
Extension Leaflet MousePosition : add documentation for coordinates edition

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#149]
Le widget d'affichage des coordonnées et de l'altitude a évolué : il est désormais possible, à l'aide d'un paramètre "editCoordinates", de localiser des coordonnées en éditant les coordonnées affichées.

Cette fonctionnalité est déjà documentée pour l'extension OpenLayers : https://github.com/IGNF/geoportal-extensions/blob/master/README-ol3.md#mp et https://jsfiddle.net/ignfgeoportail/jrL59w29/embedded/result,js,html,css/, mais elle ne l'est pas encore pour l'extension pour Leaflet.

Il faudrait : 
* ajouter la description des nouveaux paramètres dans la [documentation technique](http://ignf.github.io/geoportal-extensions/leaflet-latest/jsdoc/module-Controls.html#.MousePosition)
* décrire cette nouvelle fonctionnalité dans le [README.md](https://github.com/IGNF/geoportal-extensions/blob/master/README-leaflet.md#mp) de l'extension pour Leaflet 
* créer un exemple sur JSFiddle, à la manière de celui pour l'extension OpenLayers : https://jsfiddle.net/ignfgeoportail/jrL59w29/embedded/result,js,html,css/

**Comment by lowzonenose** [comment]
Ajout d'un exemple jsfiddle sur l’édition des coordonnées + lien ajouté dans le README
