### ISSUE TITLE
Leaflet et OL3 - SearchBar : décalages dans le positionnement avec l'autcompletion

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#151]
Je constate le PB suivant avec la barre de recherche des extensions leaflet et openlayers, reproductibles ici : 

* Leaflet : https://geoservices.ign.fr/documentation/exemples/leaflet-control-search.html
* OpenLayers : https://geoservices.ign.fr/documentation/exemples/ol3-control-search.html

Lorsqu'on saisit un texte commençant par un code postal, le service d'autocomplétion retourne parfois des suggestions ayant des coordonnées nulles. Cf. : 

`https://wxs.ign.fr/jhyvi0fgmnuxvfv0zjzorvdn/ols/apis/completion?gp-access-lib=1.0.1&text=30000%20ni&type=StreetAddress,PositionOfInterest&terr=&maximumResponses=10`

![result-autocomplete](https://user-images.githubusercontent.com/8211614/30650486-4b1d2676-9e23-11e7-9ca9-9f113a516abe.png)

C'est un bug connu du service que le widget contourne en envoyant une requête de géocodage sur le résultat avec des coordonnées nulles. C'est bien :+1: 

`https://wxs.ign.fr/jhyvi0fgmnuxvfv0zjzorvdn/geoportail/ols?gp-access-lib=1.0.1&qxml=%3C%3Fxml%20version%3D%221%2E0%22%20encoding%3D%22UTF%2D8%22%3F%3E%0A%3Cxls%3AXLS%20version%3D%221%2E2%22%0Axmlns%3Axsi%3D%22http%3A%2F%2Fwww%2Ew3%2Eorg%2F2001%2FXMLSchema%2Dinstance%22%20xmlns%3Axls%3D%22http%3A%2F%2Fwww%2Eopengis%2Enet%2Fxls%22%20xmlns%3Agml%3D%22http%3A%2F%2Fwww%2Eopengis%2Enet%2Fgml%22%20%0Axsi%3AschemaLocation%3D%22http%3A%2F%2Fwww%2Eopengis%2Enet%2Fxls%20http%3A%2F%2Fschemas%2Eopengis%2Enet%2Fols%2F1%2E2%2FolsAll%2Exsd%22%3E%0A%3Cxls%3ARequestHeader%20srsName%3D%22EPSG%3A4326%22%2F%3E%0A%3Cxls%3ARequest%20maximumResponses%3D%2225%22%20methodName%3D%22GeocodeRequest%22%20requestID%3D%22c1a406f2%2Dacc9%2D410b%2D9592%2D2aa2b0816628%22%20version%3D%221%2E2%22%3E%3Cxls%3AGeocodeRequest%20returnFreeForm%3D%22false%22%3E%3Cxls%3AAddress%20countryCode%3D%22PositionOfInterest%22%3E%3Cxls%3AfreeFormAddress%3E30000%20N%C3%AEmes%3C%2Fxls%3AfreeFormAddress%3E%3C%2Fxls%3AAddress%3E%3C%2Fxls%3AGeocodeRequest%3E%3C%2Fxls%3ARequest%3E%0A%3C%2Fxls%3AXLS%3E%0A`

Seulement, **lorsqu'on sélectionne à la souris une des propositions suggérées, on n'est pas positionné à l'endroit voulu** car il y a un décalage entre les propositions affichées et celles retournées par l'autocomplétion : 

![leaflet-autocomplete](https://user-images.githubusercontent.com/8211614/30649853-a96fd1c6-9e21-11e7-918a-966626eda58e.png)

Sur l'image ci-dessus : le service d'autocomplétion suggère la ville de Nimes (en coordonnées nulles), mais cette suggestion n’apparaît pas dans la liste proposée (première suggestion : "niac, 33430 Bazas") et si on sélectionne cette suggestion on est positionné sur la ville de Nîmes. C'est la deuxième suggestion "le niague, 33690 Grignols" qui permet de se positionner sur la première.

Le **comportement attendu** est le suivant : 

La ville de Nimes devrait apparaître en tête de liste des suggestions et il ne devrait pas y avoir de décalage.

**Comment by lowzonenose** [comment]
La ville de Nîmes est bien présente dans les résultats..., mais pas en 1ere position..., et comme on limite l'affichage aux 5 premiers résultats...
![selection_195](https://user-images.githubusercontent.com/10401006/30691216-57f5be9a-9ec7-11e7-9b47-0e262d856fa9.png)

Du fait que le résultat de l'autocompletion sur la ville de Nîmes est erroné, il est recalculé avec le geocodage puis ajouter à la liste des résultats... Malheureusement, il est ajouté à la fin de la liste déjà existante...

**Comment by lowzonenose** [comment]
![selection_196](https://user-images.githubusercontent.com/10401006/30693263-082639be-9ecf-11e7-9905-7308a4922bdb.png)

**Comment by lowzonenose** [comment]
Je reouvre car ça ne marche que pour des codes postaux ayants une seule commune...
Pour les multi commune (ex. 01100 ou 10100)..., c'est n'importe quoi...

**Comment by lowzonenose** [comment]
BUG résolu sur les multi commune pour un code postal (ex. 01100 ou 10100)
![selection_197](https://user-images.githubusercontent.com/10401006/30695006-c25a0f34-9ed6-11e7-9ae8-6702d38dc568.png)
