### ISSUE TITLE
L.geoportalControl.LayerSwitcher option

### ISSUE THREAD

**Issue by Jerome03** [IGNF/geoportal-extensions#156]
L'utilisation de GpPluginLeaflet avec la version 0.10.0-dev déclenche une  erreur avec l'option
layers>layer>config>visibility

visibility:false ne fonctionne pas (et bloque l'affichage du widget de gestion d'empilement des couches),  on ne peut utiliser que visibility:true (qui est la valeur par défault).

Une idée pour corriger ce problème ?
Merci

par exemple 
```
var layerSwitcher = L.geoportalControl.LayerSwitcher({
    	layers : [{	
        	layer : lyrOrtho,
            	config : {
            		visibility : false,
			title : "Photographies aériennes",
               		description : "Photographies aériennes"
           	 }
        }]
    });
	map.addControl(layerSwitcher);
```

**Comment by lowzonenose** [comment]
Problème avec l'option **visibility** résolu dans le ticket suivant :
https://github.com/IGNF/geoportal-extensions/issues/152
Mais il vous faudra reconstruire les binaires...

Sinon, il existe une solution de contournement (en attendant la prochaine release) sur le post suivant :
https://www.developpez.net/forums/d1752743/applications/sig-systeme-d-information-geographique/ign-api-geoportail/geoportalcontrol-layerswitcher-visibility/#post9632033

**Comment by Jerome03** [comment]
Merci pour l'info.
