### ISSUE TITLE
Extension ElevationPath : champs calculés (dénivelé, pentes, altitude maximum, ...)

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-extensions#158]
Mise en place de champs calculés pour un affichage personnalisé du profil altimétrique

 ```
{
  slopeMax :  // pente max
  slopeMoy :  // pente moyenne
  distancePlus :  // distance cumulée positive
  distanceMinus :  // distance cumulée négative
  descentPlus :  // dénivilé cumulée positive
  descentMinus :  // dénivilé cumulée négative
  altMin :  // altitude min
  altMax :  // altitude max
  distance :  // distance totale
  data : // listes d'objet elevations [{lon, lat, z, acc, dist, color}]
}
```

Actuellement, seul le champ *data* est exposé (liste des altitudes pour chaque point)

**Comment by gcebelieu** [comment]
OK pour l'évolution. 

Au niveau de l'interface de programmation du widget, je propose de rajouter ces options dans l'objet displayProfileOptions de paramétrage du widget (cf. http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.ElevationPath.html ). ça donnerait : 

```
displayProfileOptions : {
    greaterSlope : <Boolean>,
    meanSlope : <Boolean>,
    ascendingElevation : <Boolean>,
    descendingElevation : <Boolean>,
    profile : <Boolean>
}
```
avec toutes les options à true par defaut.

Ces options doivent aussi être passées aux fonctions d'affichage du graphique ([amCharts](http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.ElevationPath.html#.DISPLAY_PROFILE_LIB_AMCHARTS), [D3](http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.ElevationPath.html#.DISPLAY_PROFILE_LIB_D3) et [Default](http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.ElevationPath.html#.DISPLAY_PROFILE_BY_DEFAULT)), ce qui implique de changer la signature de ces dernières.

**Comment by lowzonenose** [comment]
Par défaut, les options suivantes sont renseignées à **true** : 
```
displayProfileOptions : {
    greaterSlope : <Boolean>,
    meanSlope : <Boolean>,
    ascendingElevation : <Boolean>,
    descendingElevation : <Boolean>,
    currentSlope : <Boolean>
}
```
Un icone d'information s'affiche sur le profil (en haut à gauche) : 
![capture1](https://user-images.githubusercontent.com/10401006/34712138-1e664864-f522-11e7-9e64-3554318a096f.PNG)

Un clic sur l'icone affiche les informations demandées : 
![capture2](https://user-images.githubusercontent.com/10401006/34712271-89f0e346-f522-11e7-98fa-451b1bb97022.PNG)

_La fenêtre d'information se ferme au clic sur l'icone ou automatiquement au bout de 4s._
