### ISSUE TITLE
PB d'affichage MousePosition OL et Leaflet

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#159]
Remontée utilisateur : 

> Quand je choisis mon système de référence, le surlignage bleuté ne se déplace pas avec ma souris (alors qu’il se déplace quand je choisis entre mètre et kilomètre).

![image001](https://user-images.githubusercontent.com/8211614/31483616-67263f40-af2d-11e7-8b1c-7fee32ada03d.png)

Reproductible ici : 

Extension OL3 : https://jsfiddle.net/ignfgeoportail/jrL59w29/embedded/result,js,html,css/

Extension Leaflet : https://jsfiddle.net/ignfgeoportail/cenwojqe/embedded/result,js,html,css/

**Comment by lowzonenose** [comment]
Sous quel OS, navigateur, ... ?
Aucun souci sous Ubuntu 14:04 avec chrome 61, firefox 57 et chromium 61...

**Comment by gcebelieu** [comment]
Je le reproduis sur mon environnement : Ubuntu + Firefox 56

**Comment by lowzonenose** [comment]
Humm..., je ne sais plus pourquoi on a fait ça....

On a mis un événement de type **'mouseover'** sur la liste des système de projection : 
```
selectSystem.addEventListener("mouseover", function (e) {
  context.onMousePositionProjectionSystemMouseOver(e);
});
```
Et ce dernier entre en conflit avec l'autre événement sur cette liste (**'change'**) : 
```
selectSystem.addEventListener("change", function (e) {
  context.onMousePositionProjectionSystemChange(e);
});
```

**Comment by lowzonenose** [comment]
Correctifs appliqués sur la branche courante...
