### ISSUE TITLE
Code postal avec les arrondissements

### ISSUE THREAD

**Issue by xPoposx** [IGNF/geoportal-extensions#163]
Bonjour,
Lorsqu'on saisie un code postal d'un arrondissement, la commune dont le code postal correspondant au code postal saisie ne s'affiche pas sur la liste proposée dans la barre de recherche. Il faudra à chaque fois saisir un code postal terminant par 00 pour que la commune s'affiche sur la liste. 
Envisagez-vous un moyen de contournement pour se problème ?

**Comment by lowzonenose** [comment]
Besoin de plus d'information sur le problème rencontré.

Exemple de recherche avec l'extension **Leaflet** sur le **code postal** _75016_ : 
![selection_222](https://user-images.githubusercontent.com/10401006/31708658-f2022932-b3ef-11e7-82e6-f66fbf9389d3.png)

**Comment by xPoposx** [comment]
Même exemple mais avec l'extension OpenLayers sur le code postal 75016:
![pasdeproposition](https://user-images.githubusercontent.com/10750004/31710306-e34059fa-b3f4-11e7-936c-802a248eafe4.PNG)
![avecproposition](https://user-images.githubusercontent.com/10750004/31710307-e359dfb0-b3f4-11e7-94f6-ac4adcef6578.PNG)

**Comment by lowzonenose** [comment]
Vous êtes sur un projet qui utilisent les extensions du Geoportail ou sur le Portail ?

**Comment by xPoposx** [comment]
Justement on aimerait effectuer une recherche par autocompletion, sachant que sur la plateforme geoportail (https://www.geoportail.gouv.fr/plan/81023/barre) on a la possibilité d'effectué une recherche en autocompletion sur les codes postaux des arrondissements.
Pour info, je crée l'objet de contrôle pour la barre de recherche de cette manière:
createSearchEngine() {
        const searchEngine = new ol.control.SearchEngine( {
            collapsed: false,
            displayAdvancedSearch: false,
            resources: {
                geocode: ['StreetAddress', 'PositionOfInterest'],
                autocomplete: ['StreetAddress', 'PositionOfInterest']
            },
            target: 'search-tool',
            zoomTo: 18
        } );
        this.map.addControl( searchEngine );
    }

**Comment by lowzonenose** [comment]
Je vais creuser mais il n'existe pas de recherche par code postal sur de l'autocompletion...
Sur le portail, on utilise une autre technologie (Service IGN **Look4**)...

**Comment by xPoposx** [comment]
Je ne comprends pas pourquoi la recherche par code postal n'existe pas pour l'autocompletion, alors que nous l'utilisons déjà et ça fonctionne bien pour les code terminant par des zéros comme je vous l'avais montré sur l'exemple précédent ?

**Comment by lowzonenose** [comment]
![selection_223](https://user-images.githubusercontent.com/10401006/31717792-a8c9bd34-b40d-11e7-83cf-96f5b7100996.png)

Nous avons bien une recherche par code postal mais avec le service de geocodage..., pas avec l'autocompletion...

**Comment by xPoposx** [comment]
Pourriez vous m'indiquer comment avez-vous fait pour implémenter cette solution sur le SearchEngine SVP ?

**Comment by xPoposx** [comment]
Je confirme que la recherche par code postal est une requête de geocodage. Je constate que dès je mets un code postal d'un arrondissement (exemple: 75010) on envoie une requête d'autocompetion et lorsque j'effectue une recherche sur un code postal terminant avec des zéros (exemple: 75000) on envoie une requête de geocode. 
Sauriez-vous me dire quelle est la source du problème ? 
Pour info, j'ai testé le cas de figure que j'ai mentionné dans les exemples dans : https://jsfiddle.net/ignfgeoportail/qpcyp8nr/embedded/result,js,html,css/ mais j'ai le même résultat.

**Comment by lowzonenose** [comment]
Ok, je confirme...
L'API bascule sur une recherche de geocodage sur des codes postaux par commune.
J'investigue sur _"pourquoi l'API ne bascule pas sur une recherche de geocodage sur des codes postaux par arrondissement"_.

**Comment by lowzonenose** [comment]
Sinon, l'extension offre la possibilité d’exécuter le geocodage sur une validation (Enter).
Ex. avec la recherche du code postal 75016 : 
![selection_225](https://user-images.githubusercontent.com/10401006/31817451-4c9be66c-b594-11e7-87cd-7f5755154d6b.png)

**Comment by xPoposx** [comment]
Quand je saisie le code postal d'un arrondissement et que j'appuie sur "entrer", la liste qui contienne les propositions ne s'affiche pas. 
![choix_du_code_postal_et_appuie_sur_enter](https://user-images.githubusercontent.com/10750004/31823801-939da00a-b5ad-11e7-9d2e-9d3c9eaff604.PNG)
Par contre il y a bien une requête de geocodage qui est lancé et qui retourne bien les informations de l'arrodissement. 
![network](https://user-images.githubusercontent.com/10750004/31823795-8ca33a1c-b5ad-11e7-9bdf-30d3c1c46ee8.PNG)

**Comment by lowzonenose** [comment]
Je remarque que vous avez modifié les css de l'extension. Essayez d'identifier la balise qui gère l'affichage de la fenêtre de résultats du geocodage...

**Comment by xPoposx** [comment]
Je me permets de vous relancer sur le sujet suite à une demande. J'aimerais savoir s'il est possible d'enlever la validation avec la touche "Entrée" et d'exécuter automatiquement la recherche en geocodage (comme c'est le cas pour la recherche en autocomplétion) pour rendre la recherche assez transparent pour l'utilisateur ?

**Comment by lowzonenose** [comment]
Oui, il est prévu de faire évoluer cette extension sur les codes postaux par arrondissement prochainement.

**Comment by lowzonenose** [comment]
@xPoposx 
Implémentation d'une recherche par geocodage (ex. sur les code postaux par arrondissement) si l'autocompletion ne trouve pas de résultats...

A minima, il faut renseigner l'option suivante pour ce fonctionnement : 
```
var search = new ol.control.SearchEngine({
  autoCompleteOptions : {
      triggerGeocode : true
  }
});
```

**Comment by xPoposx** [comment]
Merci d'avoir corriger ce bug.
J'aimerais savoir si ce correctif demande une intégration d'une nouvelle release de l'extension GP ?.  Car dans le changelog des releases, je ne trouve pas de correctif qui porte le numéro de cet issue (#163).
