### ISSUE TITLE
Navigation avec les touches du clavier

### ISSUE THREAD

**Issue by xPoposx** [IGNF/geoportal-extensions#164]
Bonjour,
Lorsqu'on saisie une adresse dans le champ de recherche, une liste de suggestion est proposée. Il est alors obligatoire de passer par la souris pour effectuer un choix dans cette liste.
Avez-vous prévu de fournir une possible à l'utilisateur de naviguer dans les propositions à l'aide des flèches haut et bas et de sélectionner l'adresse souhaité avec la touche "entrée" ?

**Comment by lowzonenose** [comment]
Oui, la _navigation au clavier_ est à prévoir sur l'extension **SearchEngine**, comme cela a été fait pour les extensions **Route** et **IsoCurve**.

**Comment by xPoposx** [comment]
Je vous remercie pour votre réponse. Sauriez-vous me dire quand cette évolution sera disponible ?

**Comment by lowzonenose** [comment]
Implémentation de la navigation clavier sur l'extension **SearchEngine** (OpenLayers & Leaflet) à prévoir prochainement...

**Comment by lowzonenose** [comment]
Correctif appliqué sur les sources du dépôt master.
Ces modifications seront disponibles dans la prochaine **release** des extensions.
