### ISSUE TITLE
L.geoportalControl.Route rechercher uniquement à partir du nom de la commune ou du lieu-dit

### ISSUE THREAD

**Issue by jbouffand** [IGNF/geoportal-extensions#165]
Bonjour,

Dans l'outil de calcul d'itinéraire, on ne peut saisir qu'une adresse complète, ou cliquer sur un point de la carte lorsqu'on ne connaît pas son adresse.

Serait-il possible de chercher les points de départ, d'étape et d'arrivée uniquement à partir d'un lieu-dit, d'un code postal ou d'un nom de commune (exactement comme dans le searchEngine)?

merci

**Comment by lowzonenose** [comment]
Recherche d'autocompletion sur une ressource de type "PositionOfInterest" uniquement, donc sur les lieu-dits et communes...
```
var route = L.geoportal.Route({
    autocompleteOptions : {
         filterOptions : {
             type : ["PositionOfInterest"]
         }
     }
});
```
Par contre, il n'y aura pas de recherche par code postal, car c'est une recherche par geocodage..., et l'extension ne l’implémente pas.

**Comment by jbouffand** [comment]
Merci beaucoup, j'ai essayé et ça marche!
