### ISSUE TITLE
Compilation sous Windows : régression (path.join)

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#167]
Actuellement, la compilation du projet rencontre des problèmes sous Windows : les différents modules ne sont pas bien chargés pour générer les bundles GpPluginxxx.js.

Il semble que ce soit un souci de chemin, et l'utilisation de 'path.join' dans le gulpfile pour gérer la compatibilité du slash entre Unix et Windows...

Pour l'issue #119 , les `path.join` avaient été remplacés par des `/` (cf. commit https://github.com/IGNF/geoportal-extensions/commit/b826a626db9c4638ebc6bf569b815acccd180294), mais dans le cadre de la PR #160, ils ont été rajoutés à certains endroits (cf. commit https://github.com/IGNF/geoportal-extensions/pull/160/commits/c3a5b1873203173c7a9c156e2d7b269178ccee9f).

**Comment by lowzonenose** [comment]
Je confirme, il y'a une régression.

**Comment by lboulanger** [comment]
Merci beaucoup, en effet ça semble bien mieux fonctionner :+1:
