### ISSUE TITLE
Compatibilité de l'extension avec OpenLayer 4.4

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#169]
Tout est dans le titre (les derniers tests datent de 4.0) : 

- tester la compatibilité
- adpater l'extension si besoin
- indiquer la compatibilité dans le README

**Comment by EPINRAP** [comment]
je suis en train de tester cette version 4.4 (avec la version 1 du GPplugin) car sur la 4.5 la couche parcellaire wfs ne se charge plus.
et il y a un bug (je ne sais pas si cela a un rapport avec ol ) :
 l'outil de mesure prends bien la mesure, mais le clic sur l'outil pour clore la mesure bloque tout

**Comment by lowzonenose** [comment]
Correctifs sur les outils de mesures (cf. Issue #181)

**Comment by gcebelieu** [comment]
@lowzonenose  : si la compatibilité de l'extension avec OL 4.4 est avérée, il faudrait  l'indiquer dans le README avant de fermer cette issue.

**Comment by lowzonenose** [comment]
Si l'on souhaite placer des coordonnées sur le quadrillage du portail ( ol.Graticule),
il nous faut basculer sur une version plus récente d'openlayers.
A minima, OL > 4.2...

_Extrait du Changelog d'openlayers :_

> v4.2.0 
> 
>     ahocevar released this on 12 Jun 2017 · 1327 commits to master since this release
> 
>     Label support for ol.Graticule
>     The ol.Graticule component has several new options to add and control the output of labels. 
>     To turn on labelling, configure ol.Graticule with showLabels: true. 
>     The new options to control label formatting are 
>     lonLabelFormatter, latLabelFormatter, lonLabelPosition and latLabelPosition.
>
