### ISSUE TITLE
Autopan à l'ouverture de pop-ups

### ISSUE THREAD

**Issue by ojathelonius** [IGNF/geoportal-extensions#170]
Bonjour,

La pop-up contenant les informations attributaires de celle-ci peut apparaître en dehors du canvas, comme dans l'exemple ci-dessous présent dans le README : 

![image](https://user-images.githubusercontent.com/11427387/33479112-2c70f9ae-d68c-11e7-988f-2f03020dc9d9.png)

Pour faciliter l'utilisation de ce widget, pourquoi ne pas mettre par défaut un autoPan avec une courte animation ? Il n'est en effet actuellement pas possible de personnaliser ceci sans modifier la librairie en elle-même.

``` javascript
map.featuresOverlay = new ol.Overlay({
    // id : id,
    element : element,
    autoPan : true, // Recentrage de la pop-up à l'ouverture si elle sort du canvas
    autoPanAnimation : {
        duration : 250 // Courte animation
    },
    positioning : "bottom-center",
    insertFirst : false, // popup appears on top of other overlays if any
    stopEvent : true
});
```

Sinon, ajouter un paramètre à displayFeature permettant à l'utilisateur de configurer l'animation à l'ouverture de la pop-up.

J'ai soumis une PR #171  pour la première solution.

**Comment by gcebelieu** [comment]
Bonjour,

Effectivement, il y a un besoin pour le recentrage des popups à l'affichage, cela nous a aussi été remonté sur le forum [developpez.net](https://www.developpez.net/forums/d1782072/applications/sig-systeme-d-information-geographique/ign-api-geoportail/declenchement-d-callback-apres-ouverture-d-popup-feature-info/). :+1: 

Merci pour votre PR. L'évolution que vous y proposez est intéressante. Cependant, comme il s'agit d'une API, je pense qu'on peut la faire évoluer en rendant le mécanisme proposé paramétrable. Je vais faire mes retours en ce sens dans #171 .
