### ISSUE TITLE
Le cursorStyle n'est pas pris en compte dans GetFeatureInfo

### ISSUE THREAD

**Issue by ojathelonius** [IGNF/geoportal-extensions#173]
Voir l'[exemple](https://jsfiddle.net/ignfgeoportail/vg6dz7bn/embedded/result,js,html,css/) du README 

Donner une valeur à cursorStyle n'a aucun effet au hover sur une feature.

Le callback de `forEachFeatureAtPixel` dans [GetFeatureInfo ](https://github.com/IGNF/geoportal-extensions/blob/master/src/Ol3/Controls/GetFeatureInfo.js#L516) n'est jamais appelé car aucune feature n'est trouvée à l'emplacement donné. Là, je sèche...

```javascript
var hit = map.forEachFeatureAtPixel(evt.pixel, function (feature, layer) {
    // Callback jamais appelé
    // Aucune feature n'est détectée au pixel donné
});
if (hit) {
    map.getTargetElement().style.cursor = gfiObj._cursorStyle;
} else {
    map.getTargetElement().style.cursor = "";
}
```

**Comment by lowzonenose** [comment]
L'exemple fonctionne...
Un exemple **jsfiddle** pour montrer le problème ?

**Comment by gcebelieu** [comment]
Dans l'exemple cité (https://jsfiddle.net/ignfgeoportail/vg6dz7bn/embedded/result,js,html,css/) il n'y a aucune couche vecteur : la couche des routes est une couche raster : 

```
var roadsLyr = new ol.layer.Tile({
        source : new ol.source.GeoportalWMS({
            layer: "TN.RoadTransportNetwork"
        })
    }) ;
```

C'est donc normal que le curseur ne se modifie pas au survol car il n'y a pas de feature. 

Pour ce type de couches raster (WMS ou WMTS), le controle GetFeatureInfo déclenche une requête "[GetFeatureInfo](https://fr.wikipedia.org/wiki/Web_Map_Service)" sur la couche à laquelle il est associée et affiche dans la popup le résultat retourné. C'est un mécanisme différent de l'interrogation des features d'une couche vecteur.
