### ISSUE TITLE
les vecteurs du widget de dessin ou des mesures persistent après fermeture du calque ou de l'outil (GpPluginOl3 v 0.12)

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#175]
bonsoir
les vecteurs du widget de dessin OL3 ou des mesures persistent après fermeture du calque ou de l'outil, et disparaissent si je clique dessus

**Comment by lowzonenose** [comment]
Un **jsfiddle** pour que je regarde de plus prêt ?

**Comment by lowzonenose** [comment]
Ce problème semble avoir été résolu, nous fermons ce ticket...
