### ISSUE TITLE
dans la wishlist : pouvoir créer des calques à volonté et pouvoir modifier le contenu de toutes les couches vecteur importées ou crées

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#176]
dans la wishlist : pouvoir créer des calques et pouvoir modifier toutes les couches vecteur importées ou crées

**Comment by gcebelieu** [comment]
Bonjour,

Il est actuellement possible de charger une couche vecteur au format KML et de la modifier avec l'outil de dessin proposé par l'extension (et d'exporter le dessin modifié en KML, et de le réimporter, et de le remodifier, etc...). L'issue suivante : https://github.com/IGNF/geoportal-extensions/issues/91 a permis de le vérifier (au prix de quelques ajustements de l'extension pour Openlayers).

Si ce n'est pas le besoin remonté par votre issue, pouvez-vous donner plus de précisions ?

Gilles

**Comment by lowzonenose** [comment]
Sans info en plus, nous fermons ce ticket...
