### ISSUE TITLE
L.geoportalControl.ReverseGeocode : tracé partiel

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#18]
L'affichage du tracé peut être partiel

![ignf_apiv3](https://cloud.githubusercontent.com/assets/2681495/16069775/4cacaf70-32d1-11e6-9f8a-3f97f5ca6abf.jpg)

`callback1465970512947({"message":null,"status":"OK","distance":"680 m","duration":"0:01:22","distanceMeters"
:"680.3","durationSeconds":"82.67","bounds":"-1.61975,48.118042;-1.617973,48.123195","geometryWkt":null
,"simplifiedWkt":null,"legs":[{"distance":"680 m","duration":"0:01:22","distanceMeters":"680.3","durationSeconds"
:"82.67","steps":[{"distance":"240 m","duration":"0:00:29","distanceMeters":"239.76","durationSeconds"
:"29.33","navInstruction":null,"name":"R DE LA GARENNE","points":["-1.619268,48.123195","-1.619216,48
.123174","-1.619272,48.123111","-1.619498,48.122872","-1.619615,48.122748","-1.61975,48.122543","-1.619739
,48.12208","-1.619733,48.12177","-1.619728,48.121564","-1.619668,48.121495","-1.619443,48.121461","-1
.619181,48.121457"]},{"distance":"322 m","duration":"0:00:38","distanceMeters":"321.56","durationSeconds"
:"38.57","navInstruction":"R","name":"R DE LA GARENNE","points":["-1.619181,48.121457","-1.619156,48
.120905","-1.619157,48.120811","-1.619159,48.120585","-1.619187,48.120476","-1.619256,48.120346","-1
.619266,48.120043","-1.619242,48.119488","-1.619191,48.119262","-1.619107,48.119172","-1.618882,48.119172"
,"-1.618591,48.119126","-1.618314,48.118994"]},{"distance":"119 m","duration":"0:00:14","distanceMeters"
:"118.98","durationSeconds":"14.77","navInstruction":"R","name":"R DE LA GARENNE","points":["-1.618314
,48.118994","-1.618356,48.118918","-1.618358,48.11877","-1.618318,48.118378","-1.618234,48.118176","-1
.61816,48.118132","-1.618012,48.118045","-1.618005,48.118042","-1.617973,48.118069"]}]}],"startDateTime"
:null,"finishDateTime":null});`

**Comment by lowzonenose** [comment]
correctif poussé sur la version 0.8.2
