### ISSUE TITLE
bug instrument de mesure avec la version 1 de GPpluginol3

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#181]
il y a un bug :
l'outil de mesure prends bien la mesure, mais le clic sur l'outil pour clore la mesure bloque tout.
debogueur
clearmesuretooltip js112
TypeError: c is undefined

**Comment by gcebelieu** [comment]
Bonjour,

Sur le fiddle suivant, les outils de la version 1.0 fonctionnent correctement (avec OL 4.0.1) :

http://jsfiddle.net/ignfgeoportail/t5qaovLm/?utm_source=website&utm_medium=embed&utm_campaign=t5qaovLm

Quelle version de OpenLayers utilisez vous ?

**Comment by EPINRAP** [comment]
Hello
oui j'ai vu que c'est une interaction click qui mettait à mal l'outil.
Mais j'ai toujours une persistance des tooltips et j'arrive pas à comprendre pourquoi
le jsfiddle
http://jsfiddle.net/ericire/u1bjfkqr/

**Comment by lowzonenose** [comment]
Je vais regarder aujourd'hui de plus prêt le problème avec les Interactions et les tooltips.

**Comment by lowzonenose** [comment]
Dans l'exemple **jsfiddle**, en replaçant le constructeur **ol.control.MousePosition** (ol) par **ol.control.GeoportalMousePosition** (geoportail), tout semble fonctionner avec les outils de mesures...

Donc quelque chose avec le contrôle MousePosition d'OpenLayers rentre en collision avec les outils de mesures.

**Comment by EPINRAP** [comment]
merci beaucoup lowzonenose pour la recherche et la solution ;)

**Comment by lowzonenose** [comment]
Correctif appliqué sur les sources du dépôt **master**.

> Nettoyage des tooltips des outils de mesures...

Ces modifications seront disponibles dans la prochaine **release** des extensions _openlayers_.
