### ISSUE TITLE
L.geoportalControl.ReverseGeocode : mise en évidence non visible

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#19]
Si la réponse n'est pas visible dans la liste des résultats, lors du survol du pointeur il est nécessaire d'utiliser l’ascenseur pour rendre visible la réponse.
Comme dès que l'on déplace la souris la mise en évidence disparait, c'est un peu compliqué.

**Comment by lowzonenose** [comment]
utilisation de [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)
