### ISSUE TITLE
Compatibilité de l'extension Leaflet avec Leaflet 1.3.0

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#190]
C'est tout récent : http://leafletjs.com/2018/01/15/leaflet-1.3.0.html

Il faudrait prévoir, pour la prochaine version de l'extension : 

1. tester la compatibilité de l'extension avec la nouvelle version
2. faire les ajustements nécessaires de l'extension pour assurer cette compatibilité
3. indiquer cette compatibilité dans le README.

**Comment by lowzonenose** [comment]
Validation de la version 1.3.0 de **leaflet** avec les extensions **geoportail** (exemples et tests de rendu valides)
