### ISSUE TITLE
Extension ElevationPath : Problème d'affichage d'un profil si la fenêtre du profil est masquée...

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-extensions#192]
`Problème d'affichage d'un profil si la fenêtre du profil est masquée lors du calcul...`

Retour de @pjjmunier issu de la PR #188 

> Pour les visus d3 et amchart :
> 
> - on active l'outil (en cliquant sur l'icone)
> - on referme la boite à outils (en cliquant sur l'icone)
> - on saisie une trace
> - on attend que le calcul soit fini
> - on rouvre la boite à outils
> 
> -> la fenêtre de résultat est vierge

> **Lowzonenose** :warning: Bug connu ! On ne peut pas afficher un profil sur un container caché (hidden ou display:none). Peut être, faudrait il empêcher de cacher le profil en cours de calcul ?

**Comment by elias75015** [comment]
Le mode replie de la fenêtre n'est plus possible. A partir du moment ou la fenetre est repliée, on repasse en mode saisie
