### ISSUE TITLE
Différence de comportement http / https selon le paramétrage de la clef

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#194]
Un utilisateur constate une différence de comportement sur l'extension leaflet :

> * quand la clé est renseignées dans data-key à l'appel du script, les requêtes sont bien effectuées en https
>  * quand la clé est renseignée dans apiKey à l'appel d'une couche WMTS (sans que data-key soit complété), les requêtes se font en http 
> 
> sachant que le site est en https.

**Comment by lowzonenose** [comment]
Je confirme...
![selection_016](https://user-images.githubusercontent.com/10401006/35293014-a9ca3662-0072-11e8-9b27-9bd5da774e82.png)

**Comment by lowzonenose** [comment]
Les services sont interrogés en fonction du protocole courant de la page en cours.
