### ISSUE TITLE
MousePosition : coordonnées sexagésimales tronquées

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#202]
Dans le widget MousePosition, la taille des input contenant les coordonnées sexagésimales est limitée à 20px (30px pour les secondes) : les coordonnées sont donc tronquées lorsqu'elles dépassent la centaine.

Par exemple, à Papeete (Polynésie Française), on se situe en longitude 149° -34' -14" O environ, mais on lit plutôt "14° -34' -14" O".
![mouseposition](https://user-images.githubusercontent.com/17139628/37905723-0effe9a6-3100-11e8-865b-c8a2e562b7b6.png)

Il faudrait modifier la taille des input (CSS commun aux extensions).

**Comment by lowzonenose** [comment]
Correctifs appliqués sur la branche courante...
