### ISSUE TITLE
Ajout type Vector tile 

### ISSUE THREAD

**Issue by germain83** [IGNF/geoportal-extensions#203]
Bonjour,

Est il possible d'ajouter le type VectorTile dans le getLayerFormat : 
if (source instanceof _ol2.default.source.VectorTile) {
            return "vector";
        }

Merci,

**Comment by pjjmunier** [comment]
Bonjour,
Merci pour votre retour.
Remarque prise en compte -> [#205](https://github.com/IGNF/geoportal-extensions/pull/205)

**Comment by lowzonenose** [comment]
correctif disponible sur l'url suivante : 
http://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers.js
http://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers-src.js
Et bientôt sur la prochaine release...
