### ISSUE TITLE
Extension Geoporatil pour iTowns : simplification de l'ajout des données Géoportail

### ISSUE THREAD

**Issue by elias75015** [IGNF/geoportal-extensions#209]
Les couches IGN quand elles sont ajoutées via l'extension Géoportail pour iTowns doivent toujours être paramétrées de manière complète, sans qu'aucune aide ne soit fournie par l'extension.

Ce parametrage qui va des légendes, aux originators, en passant par les TMS peut être très lours et fastidieux.

Il s'agit, tout comme c'est déjà le cas avec l'extension Géoportail pour OpenLayers et avec l'extension Géoportail pour Leaflet de simplifier cet ajout en se basant sur les fonctions de la bibliothèque d'accès qui permettent d'accéder à l'autoconf dynamiquement.

**Comment by lboulanger** [comment]
L'évolution est disponible depuis le 1er juin sur le dépot (cf. #213 ), et depuis la [release 2.1.0 d'iTowns](https://github.com/IGNF/geoportal-extensions/releases/tag/itowns-2.1.0) .

Pour plus d'informations, voir les documentations et exemples ci-dessous : 
[Ajout simplifié de couches WMTS Géoportail](https://github.com/IGNF/geoportal-extensions/blob/master/README-itowns.md#WMTS)
[Ajout simplifié de couches WMS Géoportail](https://github.com/IGNF/geoportal-extensions/blob/master/README-itowns.md#affichage-des-couches-wms-g%C3%A9oportail)
[Ajout simplifié de couches de relief (MNT WMTS) Géoportail](https://github.com/IGNF/geoportal-extensions/blob/master/README-itowns.md#affichage-des-couches-mnt-wmts-g%C3%A9oportail-pour-affichage-du-relief)
