### ISSUE TITLE
L.geoportalControl.Route : affichage de la durée

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#22]
Il n'est pas utile d'afficher 00h 

Les secondes ne sont pas utiles dans le cas suivant : 199h 45m 44s

**Comment by lowzonenose** [comment]
![selection_227](https://cloud.githubusercontent.com/assets/10401006/17023243/ad687fc2-4f52-11e6-97aa-277eead78404.png)
Exemple sur de courte distance
