### ISSUE TITLE
ol.control.Route : autocomplétion code postal renvoit des cordonnées nulles

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#220]
Lié à un problème connu du service d'autocomplétion, déjà mentionné (et contourné) pour le widget de recherche (#107 ) , et constaté cette fois pour le widget de calcul d'itinéraires (valable aussi pour le calcul d'isochrones / isodistances)  : 
```
Si on saisit un code postal dans la barre de recherche du widget de calcul d'itinéraires : 
les résultats d'autocomplétion ont tous des positions dont les coordonnées sont 0,0 
(on se retrouve au large de l'Afrique).
C'est un défaut du service, qu'il faut pouvoir contourner.
```

Suggestions : 
* appliquer un correctif similaire au widget de recherche (cf. #107 )
ou
* utiliser le service de recherche Look4 (https://geoservices.ign.fr/documentation/geoservices/look4.html)

**Comment by elias75015** [comment]
Report en interne --> problème de services
