### ISSUE TITLE
Erreur lors du build sous Windows

### ISSUE THREAD

**Issue by ojathelonius** [IGNF/geoportal-extensions#221]
Il y a deux problèmes à la compilation sous Windows, lié au package `jsdoc-webpack-plugin` : 

```shell
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/jsdoc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
```

Ceci est dû à deux choses : 

* le package ne peut pas appeler **jsdoc** directement, mais devrait appeler **jsdoc.cmd** à la place. Ceci est réglé dans la version 0.0.2 (bump de version nécessaire ?)
```javascript
jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc', ['-c', jsDocConfTmp]);
```

devrait être

```javascript
jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc.cmd', ['-c', jsDocConfTmp]);
```

* le package cherche `jsdoc` au mauvais endroit : 

```javascript
jsdoc = spawn(__dirname + '/node_modules/.bin/jsdoc.cmd', ['-c', jsDocConfTmp]);
```

devrait être : 

```javascript
jsdoc = spawn(path.resolve(cwd) + '/node_modules/.bin/jsdoc.cmd', ['-c', jsDocConfTmp]);
```

Le repo de `jsdoc-webpack-plugin` ne semble pas être maintenu. Faut-il considérer utiliser un autre plugin jsdoc ?

**Comment by lowzonenose** [comment]
Malheureusement, la version 0.0.2 de _jsdoc-webpack-plugin_ pose aussi quelques soucis...
Ce plugin ne me semble pas très fiable au vu du nombre de fork/publication...
le package _jsdoc-webpack-plugin-v2_ semble peut être corriger qq trucs...
