### ISSUE TITLE
[Extension OpenLayers] Conflit entre les widgets Route et Iso

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#223]
Lorsque les widgets de calcul d'itinéraires et isochrones (extension OpenLayers) sont tous les deux présents sur une même page, et que l'on déplie ou replie le panel du calcul d'itinéraires, une erreur est soulevée en console : 
![conflit-route-iso-ol](https://user-images.githubusercontent.com/17139628/43892902-974d2ea8-9bcd-11e8-9f64-e2ac6199dd3c.png)

Après analyse rapide, il s'agit d'une erreur dans la méthode Route._removeRouteStepLocations : 
* on commence par récupérer les points intermédiaires avec : 
`    var points = document.querySelectorAll("div[id^=\"GPlocationPoint\"]");
`
Or cette instruction va aussi récupérer le panel GplocationPoint du widget d'isochrones, dont l'id commence pareil.
* Ensuite, on boucle sur la liste des points sauf le premier (départ), et dernier (arrivée), sauf que le dernier est en réalité un point du calcul d'isochrones et non itinéraires (cf. ci-dessus) => il y a confusion, et on cherche à cliquer sur un élément qui n'existe pas

**Comment by lowzonenose** [comment]
@lboulanger , est ce que tu arrives encore à le reproduire ?

**Comment by lboulanger** [comment]
Oui, aussi avec les dernières versions de l'extension OpenLayers (2.0 et 2.1). Il suffit d'ajouter les deux contrôles dans une même page.
Le problème n'est pas bloquant du tout : l'outil se plie et se déplie quand même, mais l'erreur est bien présente en console.

**Comment by lowzonenose** [comment]
Corrigé sur la prochaine version...
