### ISSUE TITLE
[Extension Itowns] Ajout simplifié de couches Géoportail

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#224]
Depuis #213 , il est possible d'ajouter plus facilement des couches Géoportail avec l'extension pour Itowns.

Evolution : il faudrait rajouter un "tag" dans l'url permettant d'identifier (et comptabiliser) les requêtes émises par l'extension, par exemple _gp-it-ext_ , et pointant vers la version de l'extension utilisée
(cf. https://github.com/IGNF/geoportal-extensions/blob/master/src/OpenLayers/Layers/SourceWMTS.js#L73 pour l'extension OpenLayers par exemple)

**Comment by elias75015** [comment]
Fait depuis release 2.2.7 : https://github.com/IGNF/geoportal-extensions/releases/tag/itowns-2.2.7
