### ISSUE TITLE
Problème avec l'affichage des markers

### ISSUE THREAD

**Issue by jbouffand** [IGNF/geoportal-extensions#226]
Bonjour,

J'ai un problème avec l'affichage des markers lors de l'utilisation de la barre de recherche et du calcul d'itinéraire. Seuls l'ombre du marker apparaît, dans le meilleur des cas, tandis que le lien vers le marker proprement dit semble brisé.

J'ai essayé avec plusieurs version de Leaflet et de l'extension géoportail, et sur différents navigateurs. Le problème persiste comme vous pouvez le voir ici: [http://jbouffand.fr/cartes/cartefront/index.html](url) (exemple avec la version 1.1 de l'extension et la version 1.2 de Leaflet)

Le problème ne semble pas venir de Leaflet, dont les markers s'affichent sans problème. Quelqu'un a-t-il une solution?

Cordialement
Jérôme

**Comment by elias75015** [comment]
Bonsoir, 

désolé pour le délai de réponse beaucoup trop long.

Constatez vous toujours le problème ? Pour info l'extension Geoportail pour Leaflet est désormais en version 2.1.6.
