### ISSUE TITLE
L.geoportalControl.Route : calcul n'aboutissant pas

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#23]
Sur une demande avec une distance très importante entre 2 points, en mode piéton, le calcul n'aboutit pas.

Idem si un des points est hors de France.

Idem si un des points est sur une ile, le service rend une erreur : `ServiceException: Error in route computation Error in smartrouting Failed to execute calculateRoute com
.geoconcept.smartrouting.SmartRoutingNativeException: failed to browse direct calculated route, cannot
 get dest node id failed to browse direct calculated route, cannot get dest node id`

**Comment by lowzonenose** [comment]
> Sur une demande avec une distance très importante entre 2 points, en mode piéton, le calcul n'aboutit pas.

Oui, il est possible que le service declenche un '_timeOut_' sur un calcul trop long

> si un des points est hors de France.

 Oui, le service ne peut pas calculer un itinéraire s'il n'arrive pas à se connecter à un nœud de départ ou d'arrivé...

> si un des points est sur une ile

Le calcul est possible s'il y'a une liaison entre le nœud d'arrivé et de départ, 
ex. une liaison maritime, un pont, ...
![selection_220](https://cloud.githubusercontent.com/assets/10401006/16120847/45906c3e-33e1-11e6-9004-4b243a16ecd8.png)

**Comment by mgageo** [comment]
Pour le trajet vers une ile, j'avais fait le test entre Quiberon et Belle-Île.
Le message "Calcul en cours..." reste affiché même après la réception de l'erreur.
Il est nécessaire de recharger la page pour redisposer du contrôle, pas de bouton "abandon".

**Comment by lowzonenose** [comment]
> Le message "Calcul en cours..." reste affiché même après la réception de l'erreur.

Exact, le statut en erreur du service est mal intercepté par l'extension sur des requêtes en mode _JSONP_.
Actuellement, c'est le mode par défaut pour interroger les services.

Sur la prochaine version (> 0.8.1), le mode par défaut sera le protocole _XHR_, et toutes les exceptions seront donc correctement interceptées...

Mais il est possible de changer le protocole avec le paramètre suivant : 
`L.geoportalControl.Route({
   routeOptions : {
      protocol : 'XHR'
   }
});`

**Comment by mgageo** [comment]
J'étais déjà en version 0.8.2.
J'ai ajouté le paramètre pour le protocole, et au bout de 35 secondes (erreur 500) le message "Calcul en cours ..." disparait.

**Comment by gcebelieu** [comment]
Attention aux numéros de version. La version officielle est encore la 0.8.0.
La future version officielle sera la 0.8.1. C'est celle en cours de dev.

Il faut qu'on retire les tags 0.8.2 et 0.8.1.

**Comment by mgageo** [comment]
Pour le numéro de version, c'est le code qui me le donne.

**Comment by gcebelieu** [comment]
Oui, et il devrait donner 0.8.1 lorsqu'on utilise la version de dev. C'est à corriger.

**Comment by lowzonenose** [comment]
Pas de développement.
Le paramètre pour le protocole est donc à surcharger.
