### ISSUE TITLE
largeur de popup dans recherche inversée tronque le contenu

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#230]
bonsoir
juste un petit détail
plugin pour openlayers version 2.01 (la dernière en date pour integrer le https)
>recherche parcelles cadastrales inversées 
>le popup info sur clic du marqueur : 
> dans  CADASTRALPARCEL : le dernier chiffre de la parcelle est tronqué par la largeur affectée au popup ou est masquée par la croix de fermeture (un effet de résolution des écrans ou des caractères ?)
Je l'ai élargi dans le css à 240px et rajouté la possibilité de copier les infos (sinon à quoi servirait la recherche ?) :
.gp-features-content-div {
	min-width: 240px;
	user-select: text; 
	-moz-user-select: text;
	-webkit-user-select: text; 
	-ms-user-select: text;
	  }

**Comment by lowzonenose** [comment]
Correctif dispo sur master, prochainement sur la release 3.0.4
