### ISSUE TITLE
Problème sur la construction de l'itinéraire

### ISSUE THREAD

**Issue by gaetan79** [IGNF/geoportal-extensions#231]
Bonjour,

Pour un projet, j'utilise cette api pour tracer un itinéraire.
Mais ce dernier, passe par route interdite au voiture (rue piétonne, sens interdit).
Es-ce que cette api est toujours en développement ?

Merci de votre réponse

**Comment by elias75015** [comment]
Bonjour,

l'api de calcul d'itinéraire est toujours en version bêta, et les données ne sont pour le moment plus mises à jour. Nous espérons qu'elles le soient de nouveau en cours d'année 2019.

Pourriez vous nous fournir votre itinéraire afin de reproduire le problème (départ, arrivée, mode de transport, et endroit qui pose problème) ?
Nous pourrions ainsi référencer le problème pour correction future.

Merci

**Comment by gaetan79** [comment]
Bonjour

Merci de votre réponse rapide.
Notre itinéraire est la position actuelle à au parking du Moulin à Niort (79000).
Les paramètres de l'itinéraire sont : graph: "Voiture",
                    routePreference: "fastest",
                    apiKey: "jhyvi0fgmnuxvfv0zjzorvdn"

Par exemple La rue Ricard et la rue Victor Hugo ne sont pas autorisées pour les voitures de particuliers mais l'itinéraire nous fait passer par ces rues.
De plus, l'avenue Jacques Bujault est en sens unique mais l'itinéraire nous fait prendre cette avenue dans le sens contraire.

Merci de tenir compte des ses indications pour des corrections futures.

Bien à vous

**Comment by gaetan79** [comment]
Bonjour,

J'ai une nouvelle erreur sur mon projet.
En effet, lorsque je veux tracer l'itinéraire sur un serveur public (000webhostapp), j'ai ce message d'erreur de la console.
Savez-vous d'où cela peut-il provenir ?

![erreur](https://user-images.githubusercontent.com/44258996/53793371-08313980-3f2e-11e9-93fe-a5f41d236f46.PNG)

Merci

**Comment by lowzonenose** [comment]
Bonjour,
Vous ne pouvez pas utiliser cette clef sur votre serveur. Elle nous appartient 😉.
Veuillez faire le nécessaire pour en acquérir une sur l'espace pro.

**Comment by lowzonenose** [comment]
Cette clef est sécurisée par **referer**, et ne peut être utilisée pour votre serveur.

**Comment by gaetan79** [comment]
Bonjour,

Merci pour les informations !
J'avais trouvé cette clef sur internet c'est pour cela que je l'utilisais.
Juste une dernière question.
Je vais sur le site api.ign.fr pour trouver un clef gratuite mais je ne trouve pas comment générer cette clef.
Pouvez-vous m'aidez svp ?

Merci pour votre aide

**Comment by elias75015** [comment]
Bonjour, pour la création d'une clef, je vous invite à regarder la documentation suivante : 

https://geoservices.ign.fr/documentation/services-acces.html#comment-y-acc%C3%A9der-
et 
http://professionnels.ign.fr/tutoriel-geoservices-contractualisation

**Comment by gaetan79** [comment]
Bonjour,

Merci des informations !
