### ISSUE TITLE
Problème de logger en configuration preprod/prod

### ISSUE THREAD

**Issue by GaulthierToussaint** [IGNF/geoportal-extensions#232]
Bonjour,

J'utilise 'geoportal-extensions-leaflet' sur mon projet angular, en configuration développement je n'ai aucun problème particulier, cependant lorsque je suis en configuration préproduction ou production, mon composant qui utilise geoportal ne se charge pas j'ai une erreur dans la console qui indique `TypeError: n(...).getLogger is not a function`.

Cette erreur apparaît dans le fichier [geoportal-extensions/src/Common/Utils/Config.js](https://github.com/IGNF/geoportal-extensions/blob/master/src/Common/Utils/Config.js) à la ligne 3 `var logger = Logger.getLogger("config");`

Je ne comprends pas d'ou peut venir cette erreur lorsque je suis en environnement préproduction ou production. Est ce que comme j'utilise pour mon projet un logger particulier [@nsalaun/ng-logger](https://www.npmjs.com/package/@nsalaun/ng-logger) il pourrait y avoir une confusion entre les logger dans geoportal ?

Merci d'avance pour votre réponse

**Comment by lowzonenose** [comment]
Le passage en environnement de production sur Angular semble nettoyer des instances, classes ou lib de type Logger.
En mode production, je vous conseille d'utiliser le bundle de production, et de ne pas realiser de traitement dessus (minification, manglification ou autres). A vérifier...

**Comment by lowzonenose** [comment]
Nous avons fait le choix de désactiver le logger (mais pas de le supprimer) dans le bundle de production via la variable PRODUCTION _ à true lors de la compilation. Si vous utilisez un utilitaire de nettoyage des logger comme groundskeeper , il va falloir supprimer tous les appels à Logger, LoggerByDefault et logger.(trace|warn|debug|error|log)... La librairie est loglevel .

**Comment by AdrianPal** [comment]
Hello !

Je me permets de réagir au thread, faisant équipe avec @GaulthierToussaint. 

Nous n'utilisons pas spécialement d'utilitaire de nettoyage des loggers... Notre fichier `angular.json` pour la configuration preprod contient les instructions suivantes : 

```json
"preprod": {
  "fileReplacements": [
    {
      "replace": "src/environments/environment.ts",
      "with": "src/environments/environment.preprod.ts"
    }
  ],
  "optimization": true,
  "outputHashing": "all",
  "sourceMap": false,
  "extractCss": true,
  "namedChunks": false,
  "aot": true,
  "extractLicenses": true,
  "vendorChunk": false,
  "buildOptimizer": true
},
```

Et on utilise le plugin comme ceci : 

```ts
import { Services, LExtended as L } from 'geoportal-extensions-leaflet';

// Add cadastral parcel layer to map
Services.getConfig({
    apiKey: 'KEY',
    onSuccess: (): void => {
        this.map.addLayer(L.geoportalLayer.WMTS({
            layer: 'CADASTRALPARCELS.PARCELS',
        }, { // leafletParams
                opacity: 1,
            }));
    },
});
```

Nous avons remarqué que c'est l'utilisation de `"buildOptimizer": true` qui pose problème ; dès lors qu'il est à false, tout fonctionne comme il faut.

Auriez-vous une explication/piste de recherche ?

**Comment by lowzonenose** [comment]
Peut être regarder où Angular, avec son module d'optimisation (build-optimizer) puis sur la minification (uglify), a placé les tags `@__PURE__` dans le javascript...

**Comment by AdrianPal** [comment]
Après investigation, le problème est lié à l'utilisation de **UglifyJsWebPackPlugin** dans la config _**webpack.config.leaflet.js**_.
Dès lors qu'on enlève cette instruction, ça fonctionne parfaitement.

Le work-around qu'on utilise de nôtre côté, c'est faire appel au fichier **-src** afin d'éviter l'uglify.

Des bugs ont été recensés dans les mêmes configurations que vous utilisez (webpack 3) - voir **https://github.com/electerious/basicScroll/issues/13#issuecomment-412150683**.
