### ISSUE TITLE
Pas de marqueur sur résultat barre de recherche (SearchEngine) Leaflet

### ISSUE THREAD

**Issue by japafrite** [IGNF/geoportal-extensions#234]
Bonjour,
Pour l'exemple disponible dans la documentation :
[https://jsfiddle.net/ignfgeoportail/uLokwebc/embedded/result,js,html,css/](url)

Le marqueur résultat de la recherche ne s'affiche pas sur :
- Firefox Windows 10
- Microsoft Edge Windows 10
- Chrome Windows 10
- Safari sur IOS (Iphone 8 à jour)
- Firefox sur Android 8

Par contre sur sur Raspbian (Firefox et Chromium) il s'affiche correctement.

Pas testé sur Ubuntu ou MacOS

Cordialement

**Comment by lowzonenose** [comment]
Oups..., je confirme !!! 
Les icônes en mode **Retina**  ont été omis...

**Comment by lowzonenose** [comment]
@japafrite pourriez vous tester l'exemple suivant sur vos différents OS ?
https://geoportail.000webhostapp.com/extensions/samples/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-default.html

**Comment by lowzonenose** [comment]
Fixé sur la branche master.
Les binaires sont disponibles : 
https://ignf.github.io/geoportal-extensions/current/dist/leaflet/GpPluginLeaflet.js
En attente de release...

**Comment by japafrite** [comment]
Je confirme c'est ok sur mes systèmes qui posaient problème.
