### ISSUE TITLE
Gestion de groupe de couches

### ISSUE THREAD

**Issue by naub1n** [IGNF/geoportal-extensions#238]
Bonjour,

Est-il possible de gérer des groupes de couches dans le contrôle `layerswitcher` ?
Un utilisateur semble l'avoir fait mais il y a longtemps : https://www.developpez.net/forums/d1338125/applications/sig-systeme-d-information-geographique/ign-api-geoportail/arborescence-rendre-fonctionnel-popups-new-openlayers-layer-vector/

Ou bien à l'image de l'[extension de Matt Walker](https://github.com/walkermatt/ol-layerswitcher) qui permet d'ajouter la propriété `type` à une couche pour l'intégrer dans un groupe.

**Comment by elias75015** [comment]
Bonjour, l'evolution ne sera a priori pas intégré à notre feuille de route

Je peux vous renvoyer vers ce tte extension pour openlayers qui propose la feature que vous désirez : http://viglino.github.io/ol-ext/examples/control/map.switcher.html
