### ISSUE TITLE
ol.control.Isocurve : Passer au constructeur un layer destination

### ISSUE THREAD

**Issue by IGNBPesty** [IGNF/geoportal-extensions#241]
Bonjour,

J'aimerai utiliser le contrôleur pour créer des zones d'étude pour un projet. 

Actuellement le résultat de la requête est inséré dans une couche vectorielle temporaire et je ne sais pas trop comment y accéder.
J'aimerai pouvoir récupérer le polygone résultat, est-ce qu'il y aurait moyen de :
* passer au constructeur le nom de la couche dans laquelle on veux que le résultat vienne s'ajouter.
* ou bien avoir un déclenchement d’événement avec un lien vers la nouvelle couche.

Merci,

**Comment by lowzonenose** [comment]
Il existe une méthode publique de l'instance du composant "Isocurve" pour récupérer la couche des résultats : **Isocurve.getLayer()** (cf. http://ignf.github.io/geoportal-extensions/current/jsdoc/openlayers/ol.control.Isocurve.html).
Ensuite, à vous de la _cloner_ afin de la sauvegarder.

**Comment by IGNBPesty** [comment]
OK super, merci.
