### ISSUE TITLE
Problème d'intégration de l'extension pour Leaflet

### ISSUE THREAD

**Issue by Dimitriio** [IGNF/geoportal-extensions#243]
Bonjour,

Suite à la correction associée à l'issue #242, j'ai essayé d'importer l'extension pour **Leaflet** (Angular 7 et Typescript 3).
J'importe donc de cette manière : 
`import * as L from 'leaflet'; `
`import {Services, LExtended} from 'geoportal-extensions-leaflet';`
`ngOnInit(): void {`
`Services.getConfig({`
`      apiKey : 'jhyvi0fgmnuxvfv0zjzorvdn',`
`      timeOut : 20000,`
`      onSuccess : this.init`
`});`
`}`
Mais à la compilation, j'ai une erreur lors de l'import du style de leaflet-draw : 

> ERROR in ./node_modules/geoportal-extensions-leaflet/src/Leaflet/Styles.js
Module not found: Error: Can't resolve '../../node_modules/leaflet-draw/dist/leaflet.draw-src.css' in 'D:\Comfluence\comfluence-ui\node_modules\geoportal-extensions-leaflet\src\Leaflet'

Ainsi qu'une liste de **Module not found** :

> ERROR in ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\aws-sign2'
ERROR in ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\aws4'
ERROR in ./node_modules/ecc-jsbn/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\ecc-jsbn'
ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\http-signature\lib'
ERROR in ./node_modules/http-signature/lib/verify.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\http-signature\lib'
ERROR in ./node_modules/oauth-sign/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\oauth-sign'
ERROR in ./node_modules/request/lib/hawk.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\request\lib'
ERROR in ./node_modules/request/lib/oauth.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\request\lib'
ERROR in ./node_modules/request/lib/helpers.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\request\lib'
ERROR in ./node_modules/sshpk/lib/key.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/dhe.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/signature.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/fingerprint.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/private-key.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/identity.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/certificate.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/sshpk/lib/formats/pem.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib\formats'
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'D:\Comfluence\comfluence-ui\node_modules\request\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'http' in 'D:\Comfluence\comfluence-ui\node_modules\forever-agent'
ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'http' in 'D:\Comfluence\comfluence-ui\node_modules\http-signature\lib'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'http' in 'D:\Comfluence\comfluence-ui\node_modules\request'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'http' in 'D:\Comfluence\comfluence-ui\node_modules\tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'https' in 'D:\Comfluence\comfluence-ui\node_modules\forever-agent'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'https' in 'D:\Comfluence\comfluence-ui\node_modules\request'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in 'D:\Comfluence\comfluence-ui\node_modules\tunnel-agent'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'D:\Comfluence\comfluence-ui\node_modules\forever-agent'
ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'D:\Comfluence\comfluence-ui\node_modules\tough-cookie\lib'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'D:\Comfluence\comfluence-ui\node_modules\tunnel-agent'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in 'D:\Comfluence\comfluence-ui\node_modules\mime-types'
ERROR in ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\assert-plus'
ERROR in ./node_modules/combined-stream/lib/combined_stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\combined-stream\lib'
ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\delayed-stream\lib'
ERROR in ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\isstream'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\request'
ERROR in ./node_modules/sshpk/lib/ed-compat.js
Module not found: Error: Can't resolve 'stream' in 'D:\Comfluence\comfluence-ui\node_modules\sshpk\lib'
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'D:\Comfluence\comfluence-ui\node_modules\forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'D:\Comfluence\comfluence-ui\node_modules\tunnel-agent'
ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in 'D:\Comfluence\comfluence-ui\node_modules\request'

Ais-je oublié une étape dans l'ajout de l'extension ? 
Merci d'avance

**Comment by lowzonenose** [comment]
Mauvaise gestion de l'import CSS du plugin 'leaflet-draw' lors d'une utilisation avec les sources (import de modules ES6) sous Angular.

**Comment by Dimitriio** [comment]
Sachant que dans le fichier [Style.js](https://github.com/IGNF/geoportal-extensions/blob/master/src/Leaflet/Styles.js) du l'extension pour leaflet, on retrouve l'import de cette manière : 
`// FIXME how to do with plugin leaflet-draw !?`
`import "../../node_modules/leaflet-draw/dist/leaflet.draw-src.css";`

**Comment by lowzonenose** [comment]
Tu peux faire la modification manuelle en attendant de trouver une solution pérenne :
`import "../../node_modules/leaflet-draw/dist/leaflet.draw-src.css";`

J'ai mis un exemple de projet : **"simple-map-leaflet-angular"** sur le dépôt suivant :
https://github.com/IGNF/geoportal-third-party-integration

**Comment by lowzonenose** [comment]
fix avec la release 2.1.3

**Comment by lowzonenose** [comment]
Oups... Release 2.1.4 !!!
