### ISSUE TITLE
les ol.control ne fonctionnent plus correctement avec la version 3

### ISSUE THREAD

**Issue by pnoe** [IGNF/geoportal-extensions#244]
Bonjour,
je suis passé à la version 3.0.2 avec ol 5.3.0 et les ol.control ne fonctionnent plus correctement :
map.addControl(new ol.control.MeasureLength());
map.addControl(new ol.control.MeasureArea());
map.addControl(new ol.control.MeasureAzimuth());
map.addControl(new ol.control.ElevationPath());
les valeurs mesurées ne s'affichent pas et on ne peut terminer la saisie.
Est-ce qu'il y a des modifications suite à ce changement de version à apporter dans mon code, ou dois-je attendre des correctifs ?
Merci par avance.
Cordialement
Pierre.

**Comment by elias75015** [comment]
Bonjour,

nous ne constatons pas de problèmes particuliers sur l'affichage des résultats fournis par les outils de mesures de l'extension géoportail pour openlayers avec les dernières versions que vous citez. 

Etes-vous bien certain que votre application utilise bien les versions voulues des librairies/extensions ?
Si oui, les controls sont-ils ajoutés dans un contexte particulier ?
Pourriez-vous également nous transmettre la configuration avec laquelle les problèmes sont constatés ?

Merci,

Elias

**Comment by pnoe** [comment]
Bonjour,
suite à votre retour j'ai en effet constaté que je chargeais la version 4 et non la version 5 d'openlayers. Après correction tout fonctionne bien.
Merci beaucoup et désolé pour le dérangement.

Cordialement.
Pierre.
