### ISSUE TITLE
ol.control.Isocurve : Prérenseigner le point d'origine

### ISSUE THREAD

**Issue by IGNBPesty** [IGNF/geoportal-extensions#246]
Bonjour,

J'aimerai utiliser le composant IsoChrone en pré-renseignant en PHP la position d'origine pour l'appel au service.

Je peux modifier l'affichage de l'input, mais cela ne modifie pas la valeur interne de la position.

Dans la méthode initialize du composant on a  "this._originPoint = null;"
Est-ce qu'on pourrait ajouter une position dans les options ?

Merci,

**Comment by elias75015** [comment]
Bonjour,

effectivement, cela n'est pas possible pour l'instant. Un ticket a été créé de notre côté, mais n'est pas prioritaire dans l'immédiat.

Si cette évolution est urgente pour vous, n'hésitez pas à nous proposer une pull request (cf https://github.com/IGNF/geoportal-extensions/blob/master/CONTRIBUTING.md)

Merci pour votre remontée,

Elias

**Comment by elias75015** [comment]
Finalement, on a eu le temps :smiley: 

La PR référencée au dessus est en cours de review et sera disponible sur la prochaine release des extensions Géoportail pour OpenLayers. 

Il faudra utiliser la méthode "compute()" du control d'isocurve pour appeler le service avec les paramètres voulus via le control.

**Comment by elias75015** [comment]
La PR a été mergée sur master. Il est donc possible d'accéder au build avant la publication de la prochaine release via les urls : 
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers-src.js
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers-map.js
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers.js

**Comment by IGNBPesty** [comment]
Nickel,

Ça fonctionne pour moi.
Par contre j’ai un petit souci quand je relance un deuxième calcul, ça n’efface plus le contour précédent (je crois que ce comportement a changé, je n’en suis pas certain).

Benoit

De : elias75015 [mailto:notifications@github.com]
Envoyé : jeudi 3 octobre 2019 14:47
À : IGNF/geoportal-extensions
Cc : Benoit Pesty; Author
Objet : Re: [IGNF/geoportal-extensions] ol.control.Isocurve : Prérenseigner le point d'origine (#246)


La PR a été mergée sur master. Il est donc possible d'accéder au build avant la publication de la prochaine release via les urls :
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers-src.js
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers-map.js
https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers.js

**Comment by elias75015** [comment]
Nous venons de tester, et nous ne constatons pas le problème lorsque nous lançons plusieurs "compute" à la suite.

La fonction clear() est appelée dans "compute", et se charge de nettoyer les éventuelles couches geojson présentes sur la carte.

Pourriez-vous nous montrer plus précisément votre appel à la fonction ?

**Comment by IGNBPesty** [comment]
J’ai un bout de PHP au chargement de page qui lance le calcul :


             // Si isochrone est demandé, on affiche le widget
             <?php if (!empty($isochrone)) { ?>
                    isoControl.setCollapsed(false);

                    // Si on a une localisation, on lance un premier calcul
                    <?php if (!empty($x) && !empty($y)) { ?>
                    isoControl.compute(ol.proj.fromLonLat([<?php echo $y; ?>, <?php echo $x; ?>], projectionMercator), "15", {
                              direction : "departure",
                              method : "distance",
                              transport : "Voiture",
                              exclusions : []
                           });

                    <?php } ?>

             <?php } ?>


Il est fort probable que le problème vienne de chez moi, je travaille avec une couche vectorielle dans laquelle l’utilisateur peut intervenir et je recopie la géométrie obtenue par le composant dans cette couche. Je vais regarder ça.

Merci encore pour la fonctionnalité.

Benoit


[cid:image001.jpg@01D579FE.CEFBF310]

De : elias75015 [mailto:notifications@github.com]
Envoyé : jeudi 3 octobre 2019 15:20
À : IGNF/geoportal-extensions
Cc : Benoit Pesty; Author
Objet : Re: [IGNF/geoportal-extensions] ol.control.Isocurve : Prérenseigner le point d'origine (#246)


Nous venons de tester, et nous ne constatons pas le problème lorsque nous lançons plusieurs "compute" à la suite.

La fonction clear() est appelée dans "compute", et se charge de nettoyer les éventuelles couches geojson présentes sur la carte.

Pourriez-vous nous montrer plus précisément votre appel à la fonction ?
