### ISSUE TITLE
Extension Leaflet LayerSwitcher : Layer geoJSON

### ISSUE THREAD

**Issue by Dimitriio** [IGNF/geoportal-extensions#247]
Bonjour,

Dans notre projet, nous affichons des couches provenant de sources WFS (donc de format geoJSON). 
Ces objets n'ont pas de méthodes `setOpacity(opacity)` ce qui rend le slider inutile/inutilisable.
`ERROR TypeError: "layer.setOpacity is not a function"`
`    _onChangeLayerOpacity LayerSwitcher.js:682`
`    _createAdvancedToolOpacityElement LayerSwitcherDOM.js:503`

J'ai néanmoins réussi à trouver une solution qui serait peut être intéressante d'intégrer dans l'extension. Le style peut être éditer de la manière suivante pour le geoJSON : 
`(opacity) => geoLayer.setStyle({opacity: opacity})});`

L'option `fillOpacity` permet de modifier l'opacité à l'intérieur des Polygones, `opacity` pour les lignes.

**Comment by lowzonenose** [comment]
Correctif dispo sur master, et prochainement sur la release 2.1.5 des extensions Leaflet
