### ISSUE TITLE
[Extension OpenLayers] Compatibilité Internet Explorer

### ISSUE THREAD

**Issue by sebastien-2** [IGNF/geoportal-extensions#249]
La documentation mentionne une compatibilité IE10 et IE11 pour l'extension OpenLayers :
https://geoservices.ign.fr/documentation/utilisation_web/extension-ol.html#navigateurs-support%C3%A9s
https://github.com/IGNF/geoportal-extensions/blob/master/doc/README-openlayers.md#navigateurs-support%C3%A9s

Mais avec la dernière version de `GpPluginOpenLayers.js`, ça ne fonctionne pas dans IE11 :
Le 1er exemple de la documentation déclenche une erreur JavaScript :
https://jsfiddle.net/ignfgeoportail/j5rdjt2z/embedded/result,js,html,css/

    SCRIPT1053: Const doit être initialisé
    GpPluginOpenLayers.js (104,550720)

Apparemment à cause d'une syntaxe du style `for(const t in e)`, dans une partie du fichier possiblement en rapport avec "Mapbox".

**Comment by lowzonenose** [comment]
Je pense que ça vient de l'utilisation de l'API fetch : 
![gnome-shell-screenshot-N44SB0](https://user-images.githubusercontent.com/10401006/69721150-8369f980-1114-11ea-850e-cb02591c12a0.png)

L'utilisation d'un polyfill est à prévoir : https://github.com/github/fetch

**Comment by lowzonenose** [comment]
Compatibilité IE 10 & 11 validée sur la branche **master**...

Les bundles sont disponibles sur l'url _provisoire_ : https://ignf.github.io/geoportal-extensions/current/dist/openlayers/GpPluginOpenLayers.js

En attente de la prochaine **release**...
