### ISSUE TITLE
Problème sur getCapabilities

### ISSUE THREAD

**Issue by Toilal** [IGNF/geoportal-extensions#250]
Je ne sais pas si c'est l'endroit pour déclarer ce problème, mais j'utilise le service WMTS geoportail avec une clé d'API et OpenLayers 4.

Le problème est que, depuis peu de temps (ça fonctionnait encore hier), l'appel à getCapabilities retourne des urls via `xlink:href` sans la clé d'API fourni dans l'appel à getCapabilities, ce qui provoque par la suite des erreurs 403 sur le téléchargement des tuiles par OpenLayers car les tuiles sont téléchargées avec cette URL de base.

J'ai du implémenter un workaround pour que les couches du geoportail s'affichent normalement

```typescript
const ignWmts = 'https://wxs.ign.fr/xxx/geoportail/wmts' //xxx est a remplacé par la clé d'API 

const capabilities = await axios.get(ignWmts + '?SERVICE=WMTS&REQUEST=GetCapabilities', { responseType: 'text' })

let data = capabilities.data as string
    // Workaround pour le serveur de carto qui fourni des urls sans la clé d'API
data = data.replace(/xlink:href="https?:\/\/wxs.ign.fr\/geoportail\/wmts\?"/gm, `xlink:href="${ignWmts}?"`)

const result = wmtsCapabilities.read(data)
const wmtsOptions = wmts.optionsFromCapabilities(
  result,
  {
    layer: 'GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD.L93',
  })
```

**Comment by Toilal** [comment]
Je note aussi que le temps d'appel et de téléchargement de getCapabilities est énorme. Environ 40 secondes.

**Comment by lboulanger** [comment]
Bonjour, est-ce que vous rencontrez toujours ce problème ? Fin novembre, il y a eu des perturbations (voire indisponibilités) de certains services (cf. https://geoservices.ign.fr/blog/2019/11/28/Indispo_services_geopo.html), ça collerait donc avec ce que vous remontez (temps de chargement très long, absence de la clé dans les urls retournées par les GetCapabilities).
Si le problème est toujours présent, merci de nous le remonter !

**Comment by Toilal** [comment]
Merci pour votre retour, ça a l'air réglé en effet !
