### ISSUE TITLE
[Extension OpenLayers] Erreurs JavaScript dans les outils de mesure avec OpenLayers < 5

### ISSUE THREAD

**Issue by sebastien-2** [IGNF/geoportal-extensions#253]
[L'exemple de la documentation sur les outils de mesure](https://geoservices.ign.fr/documentation/utilisation_web/extension-ol.html#outils-de-mesures) génère des erreurs JavaScript :
https://jsfiddle.net/ignfgeoportail/cwfsLge7/embedded/result,js,html,css/

Les outils suivants sont affectés :
- Mesure d'azimut (ol.control.MeasureAzimuth)
- Mesure de surface (ol.control.MeasureArea)
- Mesure de distance (ol.control.MeasureLength)
- Profil altimétrique (ol.control.ElevationPath)

L'exemple en question utilise OpenLayers 4 (version 4.4.2).

En passant à OpenLayers 5 (j'utilise la 5.3.0), le problème disparaît.

Cela est causé par le fait que les méthodes importées de `ol/sphere` (utilisées dans la version actuelle de l'extension) ont été ajoutées dans OpenLayers à partir de la version 5.0.0 :
https://github.com/openlayers/openlayers/blob/bde6caf082aee7ecc67a268dc070fb73d05d8680/changelog/v5.0.0.md#user-content-replacement-of-olsphere-constructor-with-olsphere-functions

Il existe une solution de contournement pour ceux qui utiliseraient OpenLayers 4, qui consiste à inverser la valeur de l'option `geodesic` lors de la création des contrôles :

```javascript
new ol.control.MeasureAzimuth({geodesic: true}); // Par défaut, geodesic est à false
new ol.control.MeasureArea({geodesic: false}); // Par défaut, geodesic est à true
new ol.control.MeasureLength({geodesic: false}); // Par défaut, geodesic est à true
// Pas trouvé de contournement pour ol.control.ElevationPath
```

J'imagine que la justesse du résultat en sera affectée.

Au passage, je remarque que la condition sur l'option `geodesic` de l'outil d'azimut est inversée par rapport à l'outil de surface ou de distance.  
Comme la valeur par défaut est inversée aussi, le comportement par défaut est le même (utilisation de la sphère).  
Mais on est induit en erreur si on passe manuellement une valeur à ce paramètre.

**Comment by lowzonenose** [comment]
Modificationà faire sur les exemples **jsfiddle**

**Comment by lowzonenose** [comment]
Les exemples **jsfiddles** pointent sur la version 5.3.0 d'openlayers.
