### ISSUE TITLE
Outils de croquis - impossible de modifier l'apparence - Openlayers 6.1.1

### ISSUE THREAD

**Issue by geomoes** [IGNF/geoportal-extensions#254]
Bonjour, j'ai intégré les geoportal-extentions dans un site actualisé qui utilise la nouvelle version 6.1.1 de Openlayers. L'outil de croquis fontionne et je peux annoter, dessiner des lignes et des polygones et des markers. Les objets peuvent etre édités, mais quand je veux changer l'apparence des objets le petit dialogue ne s'ouvre pas quand je selectionne un objet. Dans la console je reçois des erreurs:
TypeError: seEv.selected[0].getStyle(...).getText is not a function    in GpPluginOpenLayers-src.js:42832:41 quand je selectionne un marker,
TypeError: seEv.selected[0].getStyle(...).getStroke is not a function        in  GpPluginOpenLayers-src.js:42875:72   quand je selectionne une ligne et
TypeError: seEv.selected[0].getStyle(...).getStroke is not a function         in GpPluginOpenLayers-src.js:42899:72  quand je selectionne un polygone

Peut-être une incomptabilité avec la nouvelle librairie de Openlayers?

**Comment by lowzonenose** [comment]
je confirme...

**Comment by lowzonenose** [comment]
Sous OpenLayers 5.3.0, la méthode `getStyle() `retourne un objet `ol/style/Style`, alors que sous la version 6.1.1, c'est une fonction qui est retourné !?

**Comment by elias75015** [comment]
API en cours de migration vers Ol6 : https://github.com/IGNF/geoportal-extensions/pull/280/files

**Comment by elias75015** [comment]
#280

**Comment by pjjmunier** [comment]
Je confirme que cela est corrigé dans la PR :
https://github.com/IGNF/geoportal-extensions/pull/280/files

**Comment by elias75015** [comment]
OK merci :+1:  Ticket à fermer quand #280 sera mergée.
