### ISSUE TITLE
Import des couches - possibilité d'éditer et de changer l'apparence

### ISSUE THREAD

**Issue by geomoes** [IGNF/geoportal-extensions#262]
Les outils de création et d'annotation offrent déjà des possibilitées avancées pour des utilisateurs, qui ne travaillent pas avec des logiciels SIG. La possibilité de pouvoir exporter les points, lignes et polygones est aussi génial et offre la possibilité de stocker et en plus de pouvoir réimporter ces géométries. Si l'utilisateur aura la possibilité de pouvoir rééditer les couches importées il aura accés à un workflow idéal, qui lui permettra d'adapter ces données continuellement.

**Comment by elias75015** [comment]
Bonjour,

tout d'abord, nous vous remercions pour l'intérêt que vous portez à nos APIs.

Votre proposition est intéressante, et en même temps très ambitieuse. Le développement à réaliser pour adapter nos outils afin de pouvoir importer, éditer, et reexporter une couche, est loin d'être trivial.

Aussi, nous engageons donc une reflexion sur l'intérêt et la faisabilité d'un tel développement de notre côté. En revanche, je ne vais pas vous cacher que nous avons que cette action n'est pas en haut de la liste de nos priorités : il ne faut pas s'attendre à ce que cette fonctionnalité soit disponible rapidement.

En attendant je peux vous proposer : 
- de consulter macarte.ign.fr, qui permet d'importer, modifier et partager un croquis aisément (mais pas de l'exporter semble t-il...)
- de spécifier ici encore plus précisément votre besoin et quelles spécifications un tel outil devrait remplir
- d'éventuellement nous proposer une Pull Request si vous en avez la motivation et la formation !

Bien cordialement,

Elias

**Comment by geomoes** [comment]
Merci de votre réponse.
Nous utilisons votre librarie pour enrichir la fonctionnalité de notre site (utilisant Openlayers 6+), qui sert à gérer des données spatiales de notre association (ONG dans le domaine de conservation de la nature au GD. de Luxembourg). Une partie de notre staff sont des utilisateurs SIG et l'autre partie fait recours à des moyens plus simples offertes par les fonctionnalités de la librairie du IGN. L'efficacité du workflow de ces utilisateurs n'est pas idéal, car les croquis peuvent être réutilisés, mais pas modifiés.
Vue que je ne suis pas un développeur professionnel, j'ai du mal à pouvoir estimer l'effort nécessaire pour introduire une telle fonctionnalité. En plus je comprends très bien, qu'une telle demande ne figure pas en haut de votre liste de priorité. Ce qui me montre que les utilisateurs du portail IGN apparemment n'ont pas demandés une telle fonctionnalité. Ou bien elle est couverte par les possibilités du portail macarte.ign.fr.
Pour répondre à une des questions:
notre besoin serait de pouvoir éditer les fichiers (*.geojson, *.kml ou *.gpx) qui puissent être importés ET d'avoir la possibilité de les exporter ensuite en même ou un autre format vectoriel.
Comme j'ai mentionné, je ne suis pas un développeur professionnel et il me semble que le chemin d'un Pull Request surpasse mes connaissances.
En tout cas, merci de votre réponse et je vais suivre le développement de votre impressionnante librairie.

**Comment by geomoes** [comment]
Merci de votre réponse.
Nous utilisons votre librarie pour enrichir la fonctionnalité de notre site (utilisant Openlayers 6+), qui sert à gérer des données spatiales de notre association (ONG dans le domaine de conservation de la nature au GD. de Luxembourg). Une partie de notre staff sont des utilisateurs SIG et l'autre partie fait recours à des moyens plus simples offertes par les fonctionnalités de la librairie du IGN. L'efficacité du workflow de ces utilisateurs n'est pas idéal, car les croquis peuvent être réutilisés, mais pas modifiés.
Vue que je ne suis pas un développeur professionnel, j'ai du mal à pouvoir estimer l'effort nécessaire pour introduire une telle fonctionnalité. En plus je comprends très bien, qu'une telle demande ne figure pas en haut de votre liste de priorité. Ce qui me montre que les utilisateurs du portail IGN apparemment n'ont pas demandés une telle fonctionnalité. Ou bien elle est couverte par les possibilités du portail macarte.ign.fr.
Pour répondre à une des questions:
notre besoin serait de pouvoir éditer les fichiers (*.geojson, *.kml ou *.gpx) qui puissent être importés ET d'avoir la possibilité de les exporter ensuite en même ou un autre format vectoriel.
Comme j'ai mentionné, je ne suis pas un développeur professionnel et il me semble que le chemin d'un Pull Request surpasse mes connaissances.
En tout cas, merci de votre réponse et je vais suivre le développement de votre impressionnante librairie.
