### ISSUE TITLE
[Extension Drawing] Evolution sur la saisie de polygones troués

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-extensions#272]
Prévoir la saisie des **multipolygones** avec ou sans trou

![image](https://user-images.githubusercontent.com/10401006/84141433-78910980-aa53-11ea-9c1f-ec7efd0103f5.png)

![image](https://user-images.githubusercontent.com/10401006/84141497-8fcff700-aa53-11ea-9e31-963317763273.png)

![image](https://user-images.githubusercontent.com/10401006/84141536-9eb6a980-aa53-11ea-80f0-a79c92713101.png)

**Comment by elias75015** [comment]
Voir turf.js : possibilité de l'ajouter à nos APIs ?
