### ISSUE TITLE
Erreur dépendances à la compilation du bundle par Webpack : fs, net et tls geoportal-extensions-leaflet 2.1.7

### ISSUE THREAD

**Issue by ygascard** [IGNF/geoportal-extensions#283]
Bonjour,

Je viens d'essayer d'intégrer l'extension leaflet dans un module ES6 compilé avec webpack et j'ai l'erreur suivante :
These dependencies were not found:

* fs in ./node_modules/request/lib/har.js
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

Ces dependances sont dépréciées et n'existent plus. Il y avait eu un ticket similaire qui a été apparemment résolu en 2.1.4 hors là avec la version 2.1.7 le problème persiste.

## Votre environnement

* Version de l'API : 2.1.7
* OS : ubuntu server

## Type d'issue
[x] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

## Contexte
Impossible de l'utiliser

**Comment by Gabriel-AL** [comment]
Bonjour,
J'ai le même souci que vous. J'aurais souhaité savoir si vous étiez parvenu à une solution, ou un "workaround".

**Comment by ygascard** [comment]
Bonjour  @Gabriel-AL 
Non, j'ai arrêté d'utiliser ce package puis mon client a finalement abandonné l'utilisation sur son site.
Désolé.

**Comment by lowzonenose** [comment]
Bonjour,

je vous renvoie vers les projets suivants : https://github.com/IGNF/geoportal-third-party-integration
C'est un dépôt d'exemples d'intégration des API Géoportail dans différents frameworks de type "Web Framework Front-End JS", tels que Angular, React, Ember, Meteor, Vue...

cf. https://github.com/IGNF/geoportal-third-party-integration/blob/master/simple-map-openlayers-angular/README.md
