### ISSUE TITLE
PB de Compatibilité IE10 (extension OL3 et Leaflet)

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#30]
Les CSS des extensions reposent sur flexbox qui est supporté jusqu'à IE10. 

Cependant, ce support par ce navigateur n'est valable qu'à certaines conditions : notamment si on préfixe les propriétés flexbox par -ms- (comme cela a été fait avec le préfixe webkit). => cf. http://caniuse.com/#feat=flexbox.

**Comment by lboulanger** [comment]
:+1: les propriétés CSS flexbox ont été préfixées par -ms- lorsque nécessaire.
Le rendu est bien meilleur sous IE10 et les widgets sont fonctionnels.

Cf. [commit 5d3d17a](https://github.com/IGNF/geoportal-extensions/commit/5d3d17aae5beafe7e7b2817f5c9fdfbfee04db82)
