### ISSUE TITLE
Erreur de compilation sur le fichier Drawing.js

### ISSUE THREAD

**Issue by RaphaelSalique** [IGNF/geoportal-extensions#300]
Bonjour,

J'utilise votre extension pour intégrer une carte à l'une des vues de mon application. 

J'obtiens l'erreur suivante à la compilation : 

```
WARN  Compiled with 1 warnings                                                                                                                                                                    
 warn  in ./node_modules/@ignf-geoportal/sdk-2d/node_modules/geoportal-extensions-openlayers/src/OpenLayers/Controls/Drawing.js
export 'LinearRing' (imported as 'LinearRing') was not found in 'ol/geom' (possible exports: Circle, Geometry, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon)
```

En ajoutant la ligne `export {default as LinearRing} from './geom/LinearRing.js';` au fichier ol/geom.js, ça fonctionne à nouveau.

**Comment by lowzonenose** [comment]
Bonjour,

quelle version du SDK utilisez vous ?

Ce problème d'export de la classe _LinearRing_ est résolu par **OpenLayers**.
La version ol v5.3.0 semble résoudre ce souci d'export...

**Comment by lowzonenose** [comment]
Je confirme que **ol v5.3.0** a un souci d'export de la classe _LinearRing_ dans l'espace de nom _ol.geom_ lors de l'utilisation dans un front-end (ex. React)...

Les API (extensions et SDK) basculent sous **ol v6.3.0** prochainement, et ce problème d'export semble être résolu.

**Comment by elias75015** [comment]
L'API est sous ol 6.3.0 désormais. Normalement, le problème est résolu.

**Comment by RaphaelSalique** [comment]
Ça marche :+1:  merci !
