### ISSUE TITLE
Services web "experts" & extension Géoportail

### ISSUE THREAD

**Issue by jwheatp** [IGNF/geoportal-extensions#308]
Bonjour,

Ce n'est pas un report de bug mais une question technique sur l'utilisation de l'extension Géoportail.

Je travaille sur un projet utilisant l'extension Géoportail pour OpenLayers pour afficher des calques en WMTS.

Jusqu'à présent, on utilisait notre "access key" pour générer un fichier autoconf.json (via [cette page](http://ignf.github.io/geoportal-access-lib/latest/jsdoc/tutorial-optimize-getconfig.html)) et on avait accès à différentes sources de données, notamment d'image satellite et de parcelle.

Ces derniers jours, on a vu [une documentation plus récente](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc) apparaître (datée de fin juillet) et on essaie de mettre à jour notre implémentation. 

On aimerait pouvoir utiliser plusieurs sources de données présentes [ici](https://geoservices.ign.fr/services-web-experts), notamment "Image aérienne" (`ortho`) et "Parcellaire" (`parcellaire`), sur une même carte (grâce à un menu de sélection de calque). On comprend que le nom des sources de données vient remplacer dans les URLs la précédente clef d'authentification.

 D'où mes questions : 
- L'extension Géoportail pour OpenLayers est-elle à jour/stable pour ce système ?
- L'utilisation d'un fichier autoconf.json est-elle toujours pertinente? (j'ai vu des exemples avec et sans)
- Comment faire pour utiliser plusieurs sources de données ("clefs") au moment de générer l'autoconf.json ?

Sources : 
https://geoservices.ign.fr/documentation/services/utilisation-web/extension-pour-openlayers
https://geoservices.ign.fr/documentation/services/utilisation-web/affichage-wmts/openlayers-et-wmts
https://geoservices.ign.fr/services-web-experts
https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc

Merci d'avance pour votre aide !

## Votre environnement
* Version de l'API : 3.0.19
* Nom du navigateur et sa version : Chrome, dernière version
* Operating System et sa version (desktop ou mobile) : Windows 10

## Type d'issue
[ ] Report de bug
[ ] Requête d'une nouvelle fonctionnalité
[x] Question

**Comment by elias75015** [comment]
Bonjour,

vos questions sont pertinentes, nous vous en remercions.

Malheureusement, nous n'avons engagé, sur les APIs JavaScript, ni le travail d'adaptation/simplification, ni le travail de documentation vis à vis de ces changements.

Cependant, comme vous allez le voir, les APIs Javascript restent viables même avec ce nouveau système d'accès aux données.

> L'extension Géoportail pour OpenLayers est-elle à jour/stable pour ce système ?

Oui, les mécanismes qui agissent derrière ne changent pas fondamentalement, et les outils nécessaire à l'utilisation de sgéoservices restent fonctionnels. Les access-keys personnelles sont toujours valables.

> L'utilisation d'un fichier autoconf.json est-elle toujours pertinente? (j'ai vu des exemples avec et sans)

Oui, l'utilisation de l'autoconf reste nécessaire (pour l'instant), que cela soit via une URL distante ou via un fichier local. 
- L'utilisation d'une URL distante permet que les données associées à la clé utilisée soient mises à jour directement.
- L'utilisation d'un fichier local sera quant à lui à privilégier quand on a besoin de stabilité (être non vulnérable aux éventuels incidents du service d'autoconf) et quand on veut utiliser plusieurs clés. C'est donc cette solution que l'on priviligiera, ce qui nous emmène à votre troisième question. 

> Comment faire pour utiliser plusieurs sources de données ("clefs") au moment de générer l'autoconf.json ?

Il est possible de générer un seul fichier d'autoconf à partir de plusieurs clés. Je vous invite à consulter [ce sujet du forum développez](https://www.developpez.net/forums/d2103545/applications/sig-systeme-d-information-geographique/ign-api-geoportail/openlayers-extension-geoportail-ol-gerer-2-cles/) ou un utilisateur explique comment il fait.

Pour résumer, afin d'obtenir un fichier d'autoconfiguration basé sur plusieurs clés, il faut appeler le service d'autoconfiguration avec une seule clé dans l'url, mais plusieurs clés derrière le paramètre keys : 
https://wxs.ign.fr/[clé A]/autoconf/?keys=[clé A, clé B, ...]&output=json&callback=callback

Par exemple, si on veut les ressources associées à la clé ortho et cartes : 
https://wxs.ign.fr/ortho/autoconf/?keys=ortho,cartes&output=json&callback=callback

Le résultat est à copier dans un fichier json que l'on appelera ensuite comme d'habitude via les APIs Javascript (cf [documentation de mise en oeuvre sur l'autoconf)](https://geoservices.ign.fr/documentation/services/utilisation-web/extension-pour-openlayers#1906)


J'espère avoir répondu à vos questions, n'hésitez pas à relancer si cela n'est pas clair. Nous essayerons de mettre à jour la documentation des APIs Javascript, et de proposer un accès plus adapté à ce nouveau système de contractualisation quand nous pourrons nous dégager un peu de temps. Mais encore une fois, les clé personnelles restent fonctionnelles.

**Comment by jwheatp** [comment]
Merci pour votre réponse très complète.

Bonne journée
