### ISSUE TITLE
Authentification HTTP et couches WMTS

### ISSUE THREAD

**Issue by sylvainpolletvillard** [IGNF/geoportal-extensions#31]
Bonjour,

Certaines couches WMTS comme ORTHOIMAGERY.ORTHOPHOTOS$GEOPORTAIL:OGC:WMTS nécessitent en plus de l'APIKey un couple login/password pour pouvoir récupérer les tiles. La documentation indique clairement comment passer l'APIKey, mais pas comment spécifier ces credentials d'authentification, ce qui fait que les requête des tiles retournent des codes HTTP 403: Forbidden.

Je n'ai rien trouvé comme paramètres d'authentification dans le code du service de configuration. Sauriez-vous comment renseigner ce login/pass pour les couches sécurisées ?

Merci d'avance

**Comment by gcebelieu** [comment]
Bonjour,

pour une utilisation web (application chargée dans un navigateur), la sécurisation à utiliser est plutôt une sécurisation par referer (URL du site de déploiement). Cf. http://professionnels.ign.fr/api-web pour obtenir de telles clefs. Les clefs sécurisées par login:password sont destinées à une utilisation dans un SIG. De ce fait, les extensions ne proposent pas de mécanisme particulier permettant de fournir cette authentification.

Si vous souhaitez néamoins utiliser une clef sécurisée par login:password pour l'application web, sachez que l'authentification est de type "Basic auth" et qu'il vous appartient de mettre en oeuvre vous même ce protocole d'authentification sur la bibliothèque utilisée.

NB : les extensions ne forgent pas les requêtes HTTP d'accès aux tuiles, c'est la classe sous-jacente de Leaflet (L.TileLayer) ou OL3 (ol.source.WMTS) qui le fait.

**Comment by sylvainpolletvillard** [comment]
Merci Gilles pour cette réponse détaillée. Notre clé API est en effet censée être configurée par referer,
Je note que ce n'est pas du ressort des extensions, nous allons investiguer de notre côté.

**Comment by sylvainpolletvillard** [comment]
Problème résolu suite à la demande d'une nouvelle clé API
