### ISSUE TITLE
Evolution : Ajouter un callback au centrage de la carte sur des coordonnées

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/geoportal-extensions#315]
Bonjour,

Serait-il possible d'ajouter une option pour définir un callback quand la carte est centrée sur des coordonnées saisies dans le contrôle `ol.control.GeoportalMousePosition` si `options.editCoordinates = true` : 
https://github.com/IGNF/geoportal-extensions/blob/2b986ad8f8d7798c1968b3ed6a1bdda26fdcca8b/src/OpenLayers/Controls/MousePosition.js#L52

Ce serait pour créer ou déplacer un Feature à cet endroit (par exemple) et pas uniquement centrer et placer le marqueur temporaire de `_markerOverlay` si celui-ci n'a pas été désactivé par `options.positionMarker.hide`.

S'il y a une meilleure façon de faire que d'ajouter une option, je suis preneur de suggestions.

**Comment by lowzonenose** [comment]
Ok, on peut ajouter une **callback** de centrage sur les coordonnées saisies.

Ex. d’implémentation : 
```js
MousePosition.prototype.onMousePositionEditModeLocateClick = function () {
(...)
// fonction
var mapCenterFunction = this.options.mapCenterCallback;
// execution...
if (typeof mapCenterFunction === "function") {
  var view = this.getMap().getView();
  var center = view.getCenter(); // on transmet les coordonnées dans la projection de la carte
  mapCenterFunction.call(this, center);
}
};
```

Ex. d'utilisation : 
```js
var mouse = new ol.control.GeoportalMousePosition({
  editCoordinates : true,
  mapCenterCallback : function (e) {
    console.log(e); // coordonnées dans la projection de la carte : ex. [222638.98158654716, 6106854.83488507]
    console.log(this.getMap()); // instance de la carte : Map
    console.log(this); // instance de l'objet MousePosition
  }
});
```

Faut il d'autres informations dans la callback ?

**Comment by slafayIGN** [comment]
Merci pour ta proposition.

En fait center n'est même pas indispensable comme paramètre car on pourrait le récupérer dans le callback avec `this.getMap().getView().getCenter()`.
