### ISSUE TITLE
Clés invalides lors de la création d'un fichier autoconf 

### ISSUE THREAD

**Issue by saxrub** [IGNF/geoportal-extensions#316]
Salut à tous
Je souhaite créer un chier autoconf pour améliorer les performances de chargement.
Pour cela, je me conforme à la doc https://github.com/IGNF/geoportal-ex...uration-locale
Mais malheureusement, je rencontre deux problèmes :
1 - si je passe par le formulaire https://ignf.github.io/geoportal-acc...getconfig.html et si j'indique les clés "cartes,administratif,calcul", je n'obtiens aucune réponse après savoir cliqué sur le bouton "Get config file"
2 - si je modifie directement l'URL proposée https://wxs.ign.fr/key1/autoconf/?ke...lback=callback la réponse est sans appel : 
{
  "http": {
    "status": 400,
    "error": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><serviceException><exception code=\"wrongKeyException\"><message>La clé renseignée n'est pas valide</message></exception></serviceException>"
  },
  "xml": null
}

**Comment by saxrub** [comment]
En complément, je peux ajouter ceci : 

1- un membre du forum developper m'a suggéré de supprimer le niveau key1 dans l'url. Dans ce cas, le fichier se crée mais il fait 13mo (300ko maxi "avant"). Chose bizarre, il contient les définitions de toutes les couches existantes même celles n'appartenant pas aux clés passées.

2- J'ai essayé aussi de remplace key1 par la première clé passée dans keys : dans ce cas, le fichier commence à ce créer mais tout se termine par un message : SyntaxError: JSON.parse: bad character in string literal at line 1 column 458351 of the JSON data

**Comment by elias75015** [comment]
Le formulaire https://ignf.github.io/geoportal-access-lib/current/jsdoc/tutorial-optimize-getconfig.html a été mis à jour pour passer plusieurs clés.

Je ferme.
