### ISSUE TITLE
Adaptation des extensions pour les API publiques (supprimer le système de clé, ou le rendre facultatif)

### ISSUE THREAD

**Issue by romain974** [IGNF/geoportal-extensions#317]
Depuis le passage en OpenData, les clés API ne sont plus indispensables. Les extensions ne sont plus fonctionnelles.

**Comment by lboulanger** [comment]
Bonjour, 

Ce n'est pas tout à fait vrai, l'utilisation des services webs ne nécessitent effectivement plus de clés personnelles (sauf quelques exceptions - SCANs IGN), mais ils sont accessibles via des URLs "prêtes à l'emploi" , qui se basent sur des clés génériques (par exemple : "essentiels", "calcul", etc.). Cf. https://geoservices.ign.fr/services-web 

Ces clés génériques (essentiels, calcul, cartes....) sont donc à passer en entrée des extensions pour le chargement de la carte, par exemple dans l'attribut "data-key" pour l'extension OpenLayers : 
`<script data-key="VOTRE-CLEF-1,VOTRE-CLEF-2,VOTRE-CLEF-3" src="chemin/vers/GpPluginOpenLayers.js"></script> `

(pour trouver les clés dont vous avez besoin, en fonction des ressources que vous voulez afficher : https://geoservices.ign.fr/documentation/services/tableau_ressources)

**Comment by romain974** [comment]
Ah effectivement, merci pour l'astuce ! C'est parfait ça

**Comment by romain974** [comment]
Fermé
