### ISSUE TITLE
L.geoportalControl.SearchEngine : réponses sans lien avec la question

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#32]
En "Recherche avancée", en ne précisant que :
- numéro
- rue
- code postal
on peut n'obtenir que des résultats avec un code postal différent.
En ajoutant la "Ville", certaines réponses n'ont aucun lien : "r du verger" versus "pl du chene germain"

**Comment by lowzonenose** [comment]
![selection_225](https://cloud.githubusercontent.com/assets/10401006/17023094/d2dd6318-4f51-11e6-9125-4601493b6cc0.png)
Exemple avec une recherche avancée sur les champs : 
- rue
- numéro
- code postal

![selection_226](https://cloud.githubusercontent.com/assets/10401006/17023119/fa79b12e-4f51-11e6-9185-ec5ba8b6795d.png)
Exemple avec une recherche avancée sur les champs : 
- rue
- numéro
- ville

**Comment by lowzonenose** [comment]
Livraison prochaine sur la version leaflet-0.8.1-dev
