### ISSUE TITLE
[Extension Measure] cloture polygone de mesure de surface impossible sous vignette mesure (tooltips)

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#321]
Bonjour,
pour la mesure de surfaces, il n'est pas possible de clore le polygone si le point est sous la vignette indiquant la mesure.
Il faudrait désactiver la copie du nombre  pendant la saisie du polygone (le rendre insélectionnable).

## Votre environnement

* Version de l'API :3.2.7
* Nom du navigateur et sa version : firefox 97
* Operating System et sa version (desktop ou mobile) : windows 10
* Lien eventuel vers votre projet :

## Type d'issue
_Retirer cette ligne : les checkboxes peuvent être cochées comme suit : [x]_
[x] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

## Pour les bugs : Etapes à suivre pour le reproduire

1.
2.
3.
4.

**Comment by lowzonenose** [comment]
Corrigé et disponible sur la prochaine **release**
