### ISSUE TITLE
Import impossible avec node.js, vite et OpenLayers

### ISSUE THREAD

**Issue by Inrap** [IGNF/geoportal-extensions#345]
**Débutant** avec cet environnement de dev : VS + vite + node.

J'arrive à importer les modules d'OpenLayers mais pas ceux de l'extension Geoportail.

## Votre environnement
* geoportal-extensions-openlayers@3.2.19
 ol@7.1.0
 vite3..9
 npm 8.19.2
* Nom du navigateur et sa version : Firefox 108
* système : Windows 10

## Type d'issue
Exemple avec GetFeatureInfo : `import GetFeatureInfo from '/node_modules/geoportal-extensions-openlayers/src/OpenLayers/Controls/GetFeatureInfo';`

erreur renvoyée : `Uncaught SyntaxError: ambiguous indirect export: default`

Je n'arrive pas à me dépêtrer de cette erreur.

**Comment by lowzonenose** [comment]
```js
import { olExtended } from "geoportal-extensions-openlayers";
var feature =  new olExtended.control.GetFeatureInfo(opts);
map.addControl(feature);
```

**Comment by Inrap** [comment]
Merci. c'est un début 🙂.
Reste à chercher dans la doc les modules que l'on peut importer.

**Comment by lowzonenose** [comment]
`import { GetFeatureInfo } from '/node_modules/geoportal-extensions-openlayers/src/OpenLayers/Controls/GetFeatureInfo';`
Ceci devrait fonctionner ?

Sinon, il est vrai que la documentation ne précise pas les modules _importable_ 
Mais, la **jsdoc** permet de connaitre les modules disponibles : https://ignf.github.io/geoportal-extensions/
