### ISSUE TITLE
Rajout des définitions du registre IGNF et enrichissement des définitions EPSG dans les extensions

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#36]
Les extensions définissent seulement le code EPSG:2154. Il faut rajouter, au chargement, la définition du registre IGNF et du registre EPSG supporté par l'API v2.

Les définitions à appliquer sont ici : https://depot.ign.fr/geoportail/crs/

**Comment by lowzonenose** [comment]
Certaines projections ne sont pas compatibles proj4 : 
cf. proj4js/proj4js#195
