### ISSUE TITLE
Impossible d'enregistrer un croquis si un label est présent

### ISSUE THREAD

**Issue by soriyathach** [IGNF/geoportal-extensions#368]
Je ne sais pas si je suis au bon endroit mais sur le site Geoportail en prod au 12/06/2023 je n'arrive pas à sauvegarder un croquis dès que j'ai ajouté un texte. J'ai une exception e.createElement is not a function sur la ligne "var a = e.createElement("LabelStyleSimpleExtensionGroup")". 

## Votre environnement

* Version de l'API : 
* /*!
 geoportal-extensions-openlayers. See https://github.com/IGNF/geoportal-extensions
 @license https://github.com/IGNF/geoportal-extensions/blob/master/LICENCE.md
 @version 3.2.21
 */
/*!
 geoportal-extensions-itowns. See https://github.com/IGNF/geoportal-extensions
 @license https://github.com/IGNF/geoportal-extensions/blob/master/LICENCE.md
 @version 2.3.10
 */
* Nom du navigateur et sa version : Chrome Version 114.0.5735.110
* Operating System et sa version (desktop ou mobile) : Windows 11 Pro 22621.1702 et macOS Ventura 13.4

## Type d'issue
[x] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

## Contexte
Il est impossible d'enregistrer un croquis dans Geoportail dès qu'un texte a été ajouté dans le croquis, il faut absolument les supprimer. 

VM1645:26934 Uncaught TypeError: e.createElement is not a function
    at i (<anonymous>:26934:84)
    at iconLabelStyle (<anonymous>:26943:117)
    at n (<anonymous>:26920:26)
    at t._writeExtendStylesFeatures (<anonymous>:26943:8)
    at t.writeFeatures (<anonymous>:26930:12)
    at t.exportFeatures (<anonymous>:28221:55)
    at <anonymous>:515:204
    at Object.update (<anonymous>:520:101)
    at HTMLButtonElement.<anonymous> (<anonymous>:1343:5)
i @ VM1645:26934
iconLabelStyle @ VM1645:26943
n @ VM1645:26920
t._writeExtendStylesFeatures @ VM1645:26943
t.writeFeatures @ VM1645:26930
t.exportFeatures @ VM1645:28221
(anonyme) @ VM1646:515
update @ VM1646:520
(anonyme) @ VM1646:1343

## Pour les bugs : Etapes à suivre pour le reproduire
Screeshot du bug : https://twitter.com/Soriya_fr/status/1668313289921527813
1. Créer un croquis
2. Créer un texte
3. Cliquer sur Enregistrer

## Comportement attendu
Le croquis devrait s'enregistrer quand je clique sur Enregistrer.

## Comportement actuel
Il ne se passe rien quand je clique sur Enregistrer si j'ai un texte dans mon croquis. Le bouton refonctionne si j'enlève les textes présents.

## Possible Cause/Correction/Solution technique (facultatif)
N/A

**Comment by lowzonenose** [comment]
Ce bug est corrigé, et ce correctif sera disponible sur la prochaine livraison du Portail

https://github.com/IGNF/geoportal-extensions/assets/10401006/c64734f7-18e0-4012-8971-1e0472fad2f1
