### ISSUE TITLE
"ol is not defined" dès l'installation de l'extension

### ISSUE THREAD

**Issue by Mysterius** [IGNF/geoportal-extensions#370]
J'ai une installation OpenLayers fonctionnelle. Je n'ai fait que rajouter le .js et le .css de l'extension dans mon fichier HTML, rien d'autre, et l'erreur suivante s'affiche dans la console du navigateur quand je charge mon site :

> Uncaught ReferenceError: ol is not defined
    at Object.<anonymous> (GpPluginOpenLayers.js:91:1334)
    at o (GpPluginOpenLayers.js:91:116)
    at Module.<anonymous> (GpPluginOpenLayers.js:108:88885)
    at o (GpPluginOpenLayers.js:91:116)
    at Object.<anonymous> (GpPluginOpenLayers.js:99:16293)
    at o (GpPluginOpenLayers.js:91:116)
    at GpPluginOpenLayers.js:91:915
    at GpPluginOpenLayers.js:91:925

* Version d'OL : 8.1.0
* Version de l'API : 2.3.4
* Nom du navigateur et sa version : Chrome 117.0.5938.134 
* Operating System et sa version (desktop ou mobile) : Windows 11 desktop

## Type d'issue
[X ] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

Je m'excuse si j'ai fait une erreur évidente. Je suis débutant en Javascript et OpenLayers est un peu obscur niveau documentations quand on n'y connait rien.

**Comment by Mysterius** [comment]
Ok, c'est juste moi qui comprend pas comment fonctionnent les choses :-).

**Comment by Mysterius** [comment]
Je pensais avoir trouvé mais non je comprends pas désolé. Quelle que soit la manière dont j'importe l'extension ça me met ce message.

**Comment by lowzonenose** [comment]
Les extensions ne sont pas encore compatible avec le version _OpenLayers_ 8.
On conseille _OpenLayers_ 6 en attendant que nous fassions l'upgrade.

**Comment by Mysterius** [comment]
Ah! Effectivement c'était indiqué dans les dépendances...
Merci pour la réponse rapide.
