### ISSUE TITLE
Utilisation directe de .container dans GPexportOpenLayers.css

### ISSUE THREAD

**Issue by bport** [IGNF/geoportal-extensions#372]
Le css de l'export openlayers (GPexportOpenLayers) contient une partie non scopée, .container input ce qui amène des effets de bord si l'on a la carte dans un élément ayant la classe container, ce qui est assez commun (bootstrap par exemple) 

Les input se retrouvent sans opacité, hauteur, largeur...

Exemple : 
https://jsfiddle.net/yb6fptd4/1/ 
- le champs de recherche, le slider de visibilité des layers...

**Comment by elias75015** [comment]
Bien vu, merci pour cette remontée.

On corrige pour la prochaine version.

**Comment by elias75015** [comment]
Corrigé par 5b0298198953cbbc050e9d4fb84586fcf3bcd78c, disponible sur extensions Géoportail pour Openlayers en version 3.4.0-beta4.

Je vous laisse nous confirmer, merci

**Comment by bport** [comment]
Merci beaucoup pour le correctif
