### ISSUE TITLE
les identifiants de parcelles ne s'affichent pas dans la recherche avancée

### ISSUE THREAD

**Issue by EPINRAP** [IGNF/geoportal-extensions#374]
il y a un bug à l'affichage des propositions de résultats de la recherche avancée parcelles cadastrales de l'extension ol version 3.3.4.
Le contenu renvoie 3 points au lieu des identifiants de parcelles et communes

## Votre environnement

* Version de l'API : 3.3.4.
* Nom du navigateur et sa version : Firefox 122.0 (64 bits)
* Operating System et sa version (desktop ou mobile) : Windows 10
* Lien eventuel vers votre projet :

## Type d'issue
_Retirer cette ligne : les checkboxes peuvent être cochées comme suit : [x]_
[x] Report de bug
[ ] Requête d'une nouvelle fonctionnalité

## Contexte

il y a un bug à l'affichage des propositions de résultats de la recherche avancée parcelles cadastrales de l'extension ol version 3.3.4.
Le contenu renvoie 3 points au lieu des identifiants de parcelles et communes

## Pour les bugs : Etapes à suivre pour le reproduire

1.
2.
3.
4.

## Comportement attendu

les identifiants de parcelles devraient s'afficher

## Comportement actuel
 il y a 3 points
![2024-01-26 10_28_18-Mozilla Firefox](https://github.com/IGNF/geoportal-extensions/assets/34379211/13c4ecdc-31d2-4e7f-8e5f-34e9fee40d57)

**Comment by elias75015** [comment]
Effectivement, il y a un problème.

Malheureusement, nous ne pousserons pas de nouvelle release avec l'ancien service de geocodage. Le problème n'est pas présent avec le nouveau service de géocodage de la Géoplateforme utilisable via les versions beta ou via la prochaine release 3.4.0.

Si toutefois vous voulez continuer d'utiliser la 3.3.4, je vous invite à modifier votre bundle et à apporter la correction (voir lien) sur la bibliothèque d'accès elle même intégrée dans les extensions pour OpenLayers : [https://github.com/IGNF/geoportal-ac...adee9e02983021](https://github.com/IGNF/geoportal-access-lib/commit/c05980a9ffc9cac9bde2fa427cadee9e02983021)
