### ISSUE TITLE
Extension Leaflet : LayerSwitcher methode addLayer ne doit pas ajouter la couche à la carte

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#4]
Le LayerSwitcher pour Leaflet expose deux méthodes : addLayer et addLayerConfig. (cf.  http://ignf.github.io/geoportal-extensions/leaflet-0.8.0/jsdoc/L.geoportalControl.LayerSwitcher.html)

Ces deux méthodes rajoutent la couche à la carte leaflet mais ce n'est pas le travail de ce composant.

* La méthode **addLayer** du LayerSwitcher doit permettre de rajouter des informations concernant une couche *existante* de la carte dans le LayerSwitcher:

=> si elle n'existe pas dans la carte : on ne fait rien
=> si la couche existe dans la carte et n'est pas dans le LayerSwitcher : on la rajoute avec les informations d'affichage (config)
=> si la couche existe dans la carte et est déjà renseignée dans le LayerSwitcher : on modifie les informations d'affichage pour cette couche dans le LayerSwitcher.

* La methode **addLayerConfig** n'a pas de raison d'être : c'est le même travail que addLayer. Il faut la déprécier.

**Comment by lowzonenose** [comment]
merge des dev. sur master : version 0.8.1 Extension Leaflet
