### ISSUE TITLE
Compatibilité IE10 : outils de croquis (ol.control.Drawing)

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#42]
Plusieurs soucis constatés sur les outils de croquis sous Internet Explorer 10 : 
- le rendu n'est pas conforme à celui des autres navigateurs et ne permet pas d'accéder à toutes les fonctionnalités 

![outils-croquis-ie10](https://cloud.githubusercontent.com/assets/17139628/17249711/8232d3c0-55a1-11e6-8a5b-a89e700421bc.png)
- lorsqu'on saisit des marqueurs ou tracés, le clic sur la croix de fermeture ou le bouton "Enregistrer" d'une popup provoque aussi l'ajout d'un marqueur à l'endroit du clic sur la carte, ce qui n'est pas souhaité
- de même pour les popups de modification des styles : on ne peut sélectionner une autre couleur car c'est le clic sur la carte qui est intercepté => fermeture de la popup.

**Comment by lowzonenose** [comment]
je n'arrive pas à les reproduire sous IE !?
Ce ticket est il toujours d'actualité ?

**Comment by lboulanger** [comment]
Oui, je le reproduis toujours sous IE10

**Comment by elias75015** [comment]
Arrêt du support IE10.
