### ISSUE TITLE
L.geoportalControl.Route : nombre de chiffres pour l'affichage de la distance

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#5]
En mode piéton, n'afficher que la valeur au kilomètre inférieur n'est pas terrible.
Sur mon test, la distance est de 1706 mètres (dixit le json) et l'affichage est de 1 km.
Est-il possible d'arrondir et mettre les valeurs en hectomètres ?

**Comment by mgageo** [comment]
Sur un autre itinéraire, j'ai une distance de 616.6 m, c'est un peu trop précis et le séparateur pour les décimales est la virgule

**Comment by lowzonenose** [comment]
commit #16
