### ISSUE TITLE
ol.control.LayerImport - WMS : couches "imbriquées" non récupérées

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#61]
Lors d'un import WMS, lorsque les couches sont organisées en catégorie (ou arborescence), seuls les titres des catégories sont affichés dans la liste des couches (alors que ce ne sont pas des couches, elles ne peuvent donc pas être ajoutées à la carte), et les couches présentes dans ces catégories ne sont pas affichées.

Par exemple : http://carto.atlasante.fr/cgi-bin/mapserv?, l'arborescence est de la forme suivante dans MapServer : 
![atlasante1](https://cloud.githubusercontent.com/assets/17139628/19078818/d2ca5c7e-8a51-11e6-863b-2ec8d75058d2.png)

alors que dans la liste des couches actuelles, seuls apparaissent les titres des catégories : 
![atlasante4](https://cloud.githubusercontent.com/assets/17139628/19078907/183f85a4-8a52-11e6-8202-0d8ea0070cd0.png)
- Solution immédiate pour afficher les couches : naviguer dans les différents niveaux d'arborescence des couches du GetCapabilities pour afficher les couches visualisables.
- Evolution : afficher les titres des catégories et les déplier au clic, pour afficher les couches de cette catégorie

**Comment by lboulanger** [comment]
Désormais l'ensemble des couches visualisables (qui ne sont pas des catégories) sont affichées.

Evolution : afficher les titres des catégories et les déplier au clic, pour afficher les couches de cette catégorie

**Comment by lowzonenose** [comment]
Mise en place d'une classification des couches par rubrique : 
![selection_045](https://user-images.githubusercontent.com/10401006/42033229-76a3bee0-7adc-11e8-9625-c654755352c6.png)

**TODO**
> - mise en place de puces *customisées*
> - gestion des messages d'erreurs d'import
> - et quelques bugs en cours...
