### ISSUE TITLE
Extension leaflet : Zoom barre de recherche 

### ISSUE THREAD

**Issue by psychicLocust** [IGNF/geoportal-extensions#63]
Sur cet exemple : http://jsfiddle.net/ignfgeoportail/uLokwebc/embedded/result,js,html,css/

1/ Dezoomer à fond (pour bien voir le problème)
2/ Chercher un lieu dans la barre de recherche
3/ Le lieu une fois trouvé, la carte se centre mais pas de zoom sur le point d'intérêt

Serait il possible de paramétrer le niveau de zoom d'arrivée à l'issue d'une recherche via la barre de recherche ?

Merci d'avance

**Comment by gcebelieu** [comment]
Ça peut se faire, l'idée serait  de proposer à la construction du widget un paramètre qui donne le choix entre, lorsqu'on choisit un résultat : 

* ne pas toucher au zoom courant (comportement actuel)
* passer sur un zoom donné par le développeur
* passer sur un zoom automatiquement déterminé en fonction de la nature du résultat

**Comment by tcoupin** [comment]
En plus des 3 valeurs de l'option zoomTo (un niveau, "min", "max"), est-ce qu'il pourrait y avoir aussi "auto" avec un calcul du zoom en fonction du résultat comme sur le Géoportail ?

**Comment by lowzonenose** [comment]
Oui, le zoom auto est prévu...

**Comment by gcebelieu** [comment]
:+1: Je rajouterais en plus la possibilité de passer une fonction qui prend en paramètre le résultat de la recherche et retourne un zoom.
L'utilisateur de l'extension aurait ainsi la possibilité de personnaliser le comportement.

**Comment by gcebelieu** [comment]
Quatre remarques sur la PR 

* je ne pense pas que les valeurs possibles "min" et "max" soient utiles (quel usage ?)

* Il faut que lorsqu'un niveau de zoom est déterminé, soit automatiquement, soit en dur via l'option zoomTo, celui-ci ne rentre pas en contradiction avec les zoom min et max de la carte. Il faut donc avant de retourner le zoom, s'il est supérieur à map.getMaxZoom(), le mettre à ce zoom max ; s'il est inférieur à map.getMinZoom(), le mettre à ce zoom min.

* Pour le calcul auto du zoom, lorsqu'on est en géocodage (ton "fixme", ligne 1026) : tu n'as pas l'information sur l'importance du lieu dans la réponse car la requête est envoyée avec le paramètre "returnFreeForm" à true. Si tu l'envoies avec la valeur false, tu auras l'importance du résultat dans la réponse. Si tu mets l'option à true dans le serviceOptions du géocodage, tu auras les valeurs pour mettre en place le zoom automatique dans ce cas.

* Autre remarque : ce paramétrage du zoom pourrait être aussi appliqué à l'extension OL3. Il faut donc rendre le code de la fonction _getZoom() réutilisable dans un espace commun aux extensions dans la mesure du possible.

**Comment by lowzonenose** [comment]
Pour résumé, 
Paramétrage du zoom (option:zoomTo) en fonction des résultats de la recherche.

Par défaut, si l'option n'est pas renseignée, on prend le zoom courant.
Les valeurs possibles sur cette option sont les suivantes :
- niveau de zoom,
- auto

Il est possible de surcharger le comportement du zoom sur un résultat via une fonction :
Ex.
```
zoomTo : function (info) {
  // traitement du zoom en fonction du type de résultat fournit par le paramètre 'info'
  // info : { 
  //   service: SuggestedLocation ou DirectGeocodedLocation, (reponse du autocompletion ou geocodage)
  //   type : StreetAddress, ..., 
  //   fields : [importance, commune, position, ...]
  // }
  return zoom;
}
```
