### ISSUE TITLE
Support complet de Leaflet 1.0

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#68]
La nouvelle version 1.0.1 de Leaflet est supportée par l'extension Géoportail.

Les exemples 1.0 ont été mis à jour avec cette dernière version, et le fichier  geoportal-extensions/samples/leaflet/UPGRADE-LEAFLET-1.0.0.md  aussi en fontion des résultats obtenus. 

Le seul problème apparent est celui de l'accès au(x) marker(s) pour le widget de positionnement (utilisé par calculs d'itinéraires et d'isochrones).

**Comment by lowzonenose** [comment]
cf. issue https://github.com/Leaflet/Leaflet/issues/4968

**Comment by gcebelieu** [comment]
Je réouvre : il y a un console.log qui traîne dans le code rajouté (IconDefault.js ligne 56)
