### ISSUE TITLE
L.geoportalControl.Route : mise en évidence sur le détail de l'itinéraire

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#7]
Lorsqu'on clique sur un segment un popup s'affiche avec le numéro du segment la distance et le temps.
Est-il possible de mettre en évidence ce segment dans le détail de l'itinéraire et sur l'itinéraire ? la mise en évidence (bleu) sur l'itinéraire disparait lors du clic.

**Comment by lowzonenose** [comment]
commit #16
