### ISSUE TITLE
Extension Leaflet LayerSwitcher : taille des widget

### ISSUE THREAD

**Issue by tcoupin** [IGNF/geoportal-extensions#72]
![widget](https://cloud.githubusercontent.com/assets/7457386/20542976/51b7257a-b104-11e6-8cf0-c55c77f43f7b.png)
Tous les widgets ne font pas la même taille : à harmoniser ?

**Comment by lowzonenose** [comment]
C'est vrai, l'extension 'layerswitcher' a une taille différente par rapport aux autres composants.

**Comment by elias75015** [comment]
Icone du LS plus grand sur toutes les extensions (LL, Ol, itowns) : 32px x 32px. Les autres icones sont en 26px x 26px. A prioriser. @azarz

**Comment by azarz** [comment]
Est-ce vraiment une demande des utilisateurs ? Le ticket n'a pas été mis à jour de puis 4 ans, il est peut être caduque.

**Comment by tcoupin** [comment]
C'est pas comme ça qu'on traite son prédécesseur ! ;)
