### ISSUE TITLE
Extension Leaflet SearchEngine : sens du widget de recherche

### ISSUE THREAD

**Issue by tcoupin** [IGNF/geoportal-extensions#73]
Par défaut, il est placé à gauche : la loupe qui sert à ouvrir et fermer ne bouge pas et c'est beau.
Je le place à droite et la loupe reste sur la gauche : je trouve ça déstabilisant.

A vous de tester : http://jsfiddle.net/tcoupin/6wgyqpqs/

**Comment by gcebelieu** [comment]
En effet.
