### ISSUE TITLE
Extensions : certains widgets ne peuvent pas apparaitre plusieurs fois sur une même page

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#74]
Il s'agit des widgets MousePosition et LayerSwitcher. Si on met deux cartes dans une même page html chacune avec un LS (par exemple), alors les intéractions avec le LS d'une carte vont aussi se produire sur l'autre.

Le PB est connu et a été corrigé sur les autres widgets : il faut "dynamiser" les ids des composants du DOM du widget, pour qu'ils ne soient pas les mêmes d'une instance d'un widget à l'autre.

Cela affecte les deux extensions (OL3 et Leaflet)

**Comment by lowzonenose** [comment]
Ok pour l'Extension **MousePosition** sous _Leaflet_ et _ol3_

**Comment by lowzonenose** [comment]
Ok pour l'Extension LayerSwitcher sous Leaflet et ol3
