### ISSUE TITLE
Extension Ol3 : outil d'import - définir un style par défaut (KML et GPX)

### ISSUE THREAD

**Issue by lboulanger** [IGNF/geoportal-extensions#76]
Dans l'outil d'import de données pour Ol3 (ol.control.LayerImport), il est possible d'importer un fichier GPX, mais le style est le style par défaut d'OpenLayers 3 : ce n'est pas très lisible.
=> Ajouter un style par défaut à la lecture du fichier GPX (en local ou via une url).
![gpx-defaultstyle](https://cloud.githubusercontent.com/assets/17139628/20590609/6a89a962-b224-11e6-9548-372d0713360e.png)

Idem pour les KML lorsqu'aucune information de style n'est renseignée.

**Comment by lboulanger** [comment]
Bonus : rendre paramétrable le style par défaut dans les options du widget, si le développeur souhaite définir un autre style par défaut.

**Comment by gcebelieu** [comment]
:+1: pour le bonus

**Comment by lowzonenose** [comment]
Rendre paramétrable le Style par défaut sur le kml 
https://github.com/openlayers/ol3/pull/1481

**Comment by lboulanger** [comment]
Correctifs apportés dans https://github.com/IGNF/geoportal-extensions/pull/79 : 
- définition de styles par défaut pour les imports GPX, et les imports KML lorsqu'aucun style n'est spécifié
- paramétrage possible de ces styles par défaut lors de la création du widget
