### ISSUE TITLE
Extension OL3 : Problèmes d'exports dûs à l'incompatibilité entre la couche dessin et la couche mesure

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#84]
Bonjour,
Tout d'abord merci et félicitations pour cette API très claire, ergonomique et pratique !

J'ai un souci lors de la sauvegarde de la couche dessin après mesure des éléments ; voici les différentes étapes pour reproduire le bug :
- Clic sur le nouvel outil de mesure de distance 'Mesure une distance'
- Clic sur l'outil de dessin 'dessiner une ligne'
- Tracer une ligne sur la carte : cette dernière apparait bien sur la carte avec la distance affichée.
* Premier souci: cela créé deux couches distinctes (ce qui est normal je pense) mais si j'essaye d'exporter les annotations, je ne sauvegarderai que la couche dessin et pas la distance affichée.
- Technique de contournement: Si je rajoute une annotation le bouton 'Ecrire sur la carte', je peux rajouter la distance à côté.
* Deuxième souci: si je déplace mon curseur sur la carte ensuite j'ai la couche de mesure qui continue de tracer un trait en pointillé et de mesurer les distance.
* Troisième souci : si je déselectionne la couche 'Mesurer une distance', je ne peux plus plus exporter la ligne et l'annotation précédemment ajoutées, que je l'ai déjà fait ou non. (**Clairement c'est bug qui est le plus important - l'export ne marche plus, s'il est utilisé après les outils de mesure**)

**Comment by gcebelieu** [comment]
Bonjour,
merci pour l'intérêt que vous portez à cette API.

Tout d'abord, effectivement, les mesures effectuées par les outils proposés ne sont pas exportables, seuls les outils de dessins permettent de sauvegarder une couche comme vous l'avez bien remarqué.
Pour permettre cela, il faudrait à mon avis faire évoluer les outils de dessin pour qu'ils embarquent la mesure de distance et de surface lorsqu'on trace une ligne ou un polygone et l'affichent comme texte par défaut dans la la popup à la fin du tracé. C'est à étudier.

Pour l'incompatibilité entre les outils de dessin et ceux de mesures, je pense que les interactions OL3 créées pour chacun des outils entrent en conflit lorsqu'elles sont sollicitées en même temps : là on est plutôt dans le domaine du bug => normalement l'activation d'un outil devrait désactiver proprement un autre outil en cours.

**Comment by gcebelieu** [comment]
J'ai créé un fiddle pour reproduire les comportements énoncés : 

http://jsfiddle.net/ignfgeoportail/z8sLj559/embedded/result,js,html/

Pour contourner votre problème : plutôt que d'écrire la distance sur la carte pour la sauvegarder sur la couche de dessin, vous pouvez écrire le résultat de la mesure dans la popup à la fin du tracé (à défaut de le remplir automatiquement). Vous pourrez ensuite sauvegarder un peu plus sereinement votre couche.

**Comment by F3L1X79** [comment]
Merci pour le fiddle et la solution de contournement, mais le problème c'est que je ne serai pas seul à utiliser cette solution, et il me sera impossible d'en avertir chaque personne de l'utiliser de cette façon systématiquement.
Je n'hésiterai pas à ajouter ma solution ici si je trouve à écrire un code adéquat pour contourner le problème d'ici là.
