### ISSUE TITLE
[Question] : Renommer les éléments automatiquement ajoutés à la couche LayerSwitcher après instanciation de la carte ?

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#85]
Si par le biais d'un évément j'ajoute une couche quelconque (longtemps après instanciation de ma map et des différents composants) :

                  var kmlToLoad = {kml: '<kml>Un KML complet</kml>'};

                  var vectorSource = new ol.source.Vector({
                        opacity: 1,
                        visible: true
                    });

                    var features = new ol.format.KML().readFeatures(
                        kmlToLoad.kml,
                        {
                            dataProjection: 'EPSG:4326',
                            featureProjection: mapToLoad.getView().getProjection()
                        });
                    vectorSource.addFeatures(features);

                    var vector = new ol.layer.Vector({
                        id: 123,
                        title: 'Test de titre',
                        source: vectorSource,
                        visible: true,
                    });

                    map.addLayer(vector);

La couche LayerSwitcher se met bien à jour avec la nouvelle couche (qu'il est possible de supprimer et d'en mesurer l'opacité) mais je ne vois pas comment mettre à jour le titre de la couche nouvellement ajoutée (qui reste un numéro) pour le LayerSwitcher. Il semble que l'attribut 'title' et 'name' ne soient pas pris en compte.
Et `vector.set('name', 'Test titre') ou vector.set('title', 'Test titre') `ne fonctionnent pas non plus.

Merci d'avance pour l'aide apportée.

**Comment by gcebelieu** [comment]
Bonjour,
il faut utiliser la méthode [addLayer](http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.LayerSwitcher.html#addLayer) du LayerSwitcher pour rajouter les infos de configuration sur la nouvelle couche.

**Comment by F3L1X79** [comment]
Merci !
Je ferme le ticket.
