### ISSUE TITLE
L.geoportalControl.Route : changement de comportement du mode "Pointer le lieu"

### ISSUE THREAD

**Issue by mgageo** [IGNF/geoportal-extensions#9]
Sur le pointage initial, les coordonnées sont transformées en adresse, ensuite lors du déplacement du marqueur, cette transformation n'est plus faite.

**Comment by gcebelieu** [comment]
Effectivement, c'était pour pouvoir "débrayer" l'accrochage du marker sur une adresse lorsqu'on ne le souhaite pas.
Le bon comportement peut être le suivant : offrir la possibilité à l'internaute de "débrayer" le géocodage inverse en maintenant la touche CTRL (par exemple) enfoncée lors du (dé)placement du marker.

**Comment by lowzonenose** [comment]
mise en place sur la version leaflet 0.8.1 (dev)
