### ISSUE TITLE
Extension OL3 : Récupérer la couche de dessin après import des données pour vision des légendes et édition

### ISSUE THREAD

**Issue by F3L1X79** [IGNF/geoportal-extensions#91]
Actuellement sur OL3 (et je pense que c'est pareil avec leaflet, mais pas vérifié) lorsque l'on exporte des annotations avec la couche dessin IGN (au format KML donc) et qu'on les importe avec le module d'import IGN - on ne peut plus modifier ces annotations, ni même voir le texte de légende ajouté dans la popup après ajout d'un marqueur par exemple.

Y aurait-il des solutions de contournement relativement simples à mettre en place ? (par exemple l'interception d'un événement IGN lié à cette couche de dessin importée)
Merci d'avance.

Edit: problème peut-être en partie lié à https://github.com/IGNF/geoportal-extensions/issues/89

**Comment by gcebelieu** [comment]
Les outils de dessin et d'import sont indépendants. Pour pouvoir éditer une couche KML (ou GPX, ou toute couche de type ol.layer.Vector), il vous suffit de passer cette couche à la fonction setLayer() de l'outil de dessin :

http://ignf.github.io/geoportal-extensions/ol3-latest/jsdoc/ol.control.Drawing.html#setLayer

Ce sera alors cette couche où l'outil enregistrera (et donc éditera) les objets dessinés.

**Comment by F3L1X79** [comment]
Merci beaucoup !

**Comment by gcebelieu** [comment]
Pouvez-vous nous fournir le code mis en œuvre (sur un fiddle se serait idéal) pour qu'on puisse regarder ?

**Comment by F3L1X79** [comment]
Le fiddle en question :  http://jsfiddle.net/krj9yp6f/3/

La manipulation à faire:
- ajouter plusieurs annotations sur la carte (idéalement un marqueur, une surface et une annotation type texte)
- Cliquer sur le bouton sauvegarder (chez moi ça sauvegarde en base, mais pour le fiddle je le fais sauvegarder dans un input type 'hidden') -> Cela a pour effet d'effacer les derniers layers ajoutés - c'est voulu (dans mon cas je souhaite repartir d'un map vierge également).
- Cliquer sur le bouton Charger
- Ouvrir à nouveau le contrôle de dessin, et essayer de les modifier avec "Modifier l'apparence des objets" et "Modifier les textes / infobulles" -> on a bien les erreurs suivantes : 
`TypeError: t.selected[0].getStyle(...).getStroke is not a function`
et
`TypeError: t.selected[0].getStyle(...).getText is not a function`

Question subsidiaire : en rechargeant les données on voit qu'on perd les styles pour les annotations de type 'texte' (la police semble rétrécir) et j'ai le même souci avec mes marqueurs custos ajoutés à partir d'un .png (ils sont rétrécis). j'ai essayé de modifier les attributs de l'objet KML:
```
 var features = new ol.format.KML({
                        showPointNames: true,
                        extractStyles: true,
                        writeStyles: true
                    }).readFeatures(
                        kml,
                        {
                            dataProjection: 'EPSG:4326',
                            featureProjection: mapToLoad.getView().getProjection()
                        });
```
mais rien n'y fait. Une idée également ?

**Comment by gcebelieu** [comment]
Voici quelques éléments :

* lorsque vous créez la source Vecteur, il faut qu'elle ait une propriété features (ol.Collection) qui va héberger les features que vous allez rajouter. Sinon l'outil de dessin n'aura pas de container pour stocker les annotations :

```
var vectorSource = new ol.source.Vector({
          opacity: 1,
          features : new ol.Collection(),
          visible: true
        });
```

* Pour les styles des annotations, effectivement, c'est un défaut du parser KML d'OpenLayers qui ne restitue pas tous les styles saisis avec l'outil de dessin. L'extension OL3 propose une surcharge de ce parser (non documentée, c'est un tort) pour corriger cela (entre autres) : ol.format.KMLExtended

en utilisant cette classe les styles seront correctement restitués. 

Vous pouvez voir les résultats sur ce fiddle issu du votre où j'ai posé les corrections ci-dessus :

http://jsfiddle.net/vsd79ktr/embedded/result,js,html/

**Comment by F3L1X79** [comment]
Merci beaucoup !
Tout fonctionne beaucoup mieux, excepté pour les erreurs liés à la modification des marqueurs (styles et description - j'ai toujours `t.selected[0].getStyle(...).getText is not a function`).
Si vous trouvez une solution pour ce dernier point je suis preneur; en attendant je pense qu'on peut considérer le ticket comme clos.

**Comment by F3L1X79** [comment]
Bonjour,
Finalement je me permets de réouvrir le ticket pour la seconde fois (désolé), car quand je souhaite à nouveau sauvegarder les données nouvellement re-chargées, j'ai la même erreur que lorsque j'essai d'éditer les styles des marqueurs, à savoir : 
```
TypeError: t.getStyle(...).getText is not a function
    at c (GpPluginOl3.js:100)
    at r (GpPluginOl3.js:100)
    at o._writeExtendStylesFeatures (GpPluginOl3.js:100)
    at o.writeFeatures (GpPluginOl3.js:100)
    at a.exportFeatures (GpPluginOl3.js:104)
    at AppComponent.saveToDatabase (app.component.ts:408)
    at View_AppComponent1.handleEvent_2 (component.ngfactory.js:382)
    at SafeSubscriber.schedulerFn [as _next] (forms.umd.js:1568)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:238)
    at SafeSubscriber.next (Subscriber.ts:190)
```

J'ai mis à jour le fiddle afin de montrer l'erreur : http://jsfiddle.net/krj9yp6f/9/embedded/result,js,html/ . Il suffit d'essayer de sauvegarder une seconde fois après avoir chargé une première fois les données.

**Comment by lowzonenose** [comment]
Fix mis en place sur la lecture/écriture des KML.
Les bundles sont à jour sur **depot.ign.fr**.
Ceci peut donc être validé sur le jsfiddle :  http://jsfiddle.net/krj9yp6f/9/embedded/result,js,html/

**Comment by F3L1X79** [comment]
Merci beaucoup pour le patch, mais il semble que l'erreur reste présente lorsque l'on essaye d'éditer les marqueurs (couleur et infobulles) après les avoir rechargés.

**Comment by lowzonenose** [comment]
Fix mis en place sur la gestion de la lecture des **marker** KML, _avec application des bons styles aux features_ !
Les bundles sont à jour sur **depot.ign.fr.**
Ceci peut donc être validé sur le jsfiddle : http://jsfiddle.net/krj9yp6f/9/embedded/result,js,html/

**Comment by gcebelieu** [comment]
ça marche pour les markers et les labels : c'est chouette :)

Par contre, sur le fiddle, je vois qu'il y a un problème lorsqu'on édite les styles des lignes et polygones &près rechargement du KML... j'ai l'erreur suivante : 

```
TypeError: t.selected[0].getStyle(...).getStroke is not a function
https://depot.ign.fr/geoportail/extensions/ol3/develop/bin/GpPluginOl3.js
Line 105
```

on l'aura un jour... :)

**Comment by lowzonenose** [comment]
L'édition des lignes et polygones, ça marchait avant la modif ?

**Comment by F3L1X79** [comment]
Ça marchait il y a un mois c'est sûr, mais pas depuis les dernières modifications d'hier je crois.

**Comment by F3L1X79** [comment]
Je viens de vérifier, et non ça ne marchait pas avant non plus. Modifier les infobulles a toujours marché sur les lignes, mais pas "modifier l'apparence des objets".

**Comment by lowzonenose** [comment]
Tout semble fonctionnel...
