### ISSUE TITLE
OL3 : widget elevationPath

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/geoportal-extensions#93]
les dernières modifs sur le rendu du widget elevationPath ont introduit quelques débordements au niveau de l'affichage (visible ici) :

http://jsfiddle.net/ignfgeoportail/cwfsLge7/embedded/result,js,html,css/

n'y aurait-il pas un oubli de règles css ?

**Comment by lowzonenose** [comment]
débordement ? règles CSS ? 
![selection_078](https://cloud.githubusercontent.com/assets/10401006/21617309/c32a363c-d1e5-11e6-80f7-eb75cac5a300.png)
Tu attendais un autre rendu ?

**Comment by gcebelieu** [comment]
j'ai un débordement de l'affichage de la distance sous ff :

![rendu-ff](https://cloud.githubusercontent.com/assets/8211614/21634225/dae8e3a2-d255-11e6-97f5-2628306ac813.png)

et ie 11 :

![rendu-ie11](https://cloud.githubusercontent.com/assets/8211614/21634229/e0122514-d255-11e6-962c-7a54672e1aec.png)

**Comment by lowzonenose** [comment]
FF avec extension ol : 
![selection_080](https://cloud.githubusercontent.com/assets/10401006/21651870/a1d03052-d2aa-11e6-9897-bfb2d74775f8.png)

FF avec extension leaflet : 
![selection_079](https://cloud.githubusercontent.com/assets/10401006/21651883/b142d5e4-d2aa-11e6-8da9-38723e4a41f1.png)

**Comment by lowzonenose** [comment]
IE avec extension ol : 
![selection_082](https://cloud.githubusercontent.com/assets/10401006/21652302/6e68ffa8-d2ac-11e6-88b3-bde57a9bc673.png)

IE avec extension leaflet : 
![selection_081](https://cloud.githubusercontent.com/assets/10401006/21652313/7bfb1b42-d2ac-11e6-8bcf-073170dfd18a.png)
