### ISSUE TITLE
Creation du fichier autoconf.json

### ISSUE THREAD

**Issue by Jerome03** [IGNF/geoportal-extensions#94]
Bonjour
Dans la procédure d'installation de l'extension Géoportail il est indique pour configurer l'accès à la plateforme Géoportail (dans le cas d'un configuration locale) que l'on peut utiliser le formulaire dans la page
http://ignf.github.io/geoportal-access-lib/latest/jsdoc/tutorial-optimize-getconfig.html
Je ne récupère aucun fichier via ce formulaire. En faisant des recherches j'ai trouvé que l'on peut obtenir un fichier autoconf.json via l'adresse
http://wxs.ign.fr/[clé]/autoconf/?output=json&callback=OpenLayers.Protocol.Script.registry.regId1
J'ai alors un message d'erreur dans la console 
Uncaught ReferenceError: OpenLayers is not defined
Le fichier .json commence  par OpenLayers.Protocol.Script.registry.regId1, pour leaflet ne devrait il pas commencer par autre chose OpenLayers me semblant être justement pour l'extension OpenLayers ?

Merci

Jérôme

**Comment by gcebelieu** [comment]
Bonjour,
il y avait effectivement un problème dans la page de génération de fichier de configuration issu d'une évolution récente de la bibliothèque d'accès utilisée. Le problème est corrigé : la page re-fonctionne désormais normalement.

NB : vous pouvez effectivement fabriquer vous même le fichier de configuration local en invoquant le service que vous mentionnez mais l'URL à utiliser est désormais la suivante (pour être comprise par les extensions et le SDK) :

http://wxs.ign.fr/%5Bcl%C3%A9%5D/autoconf/?output=json&callback=callback

**Comment by Jerome03** [comment]
Merci
