### ISSUE TITLE
Préfixage classe CSS GPmeasureToolTip.css

### ISSUE THREAD

**Issue by sylvainpolletvillard** [IGNF/geoportal-extensions#96]
Bonjour,

Nous avons observé une régression de style depuis une mise à jour de l'extension OL3. Elle vient de cette classe "tooltip" que nous utilisons également dans notre application: https://github.com/IGNF/geoportal-extensions/blob/master/res/common/GPmeasureToolTip.css#L3

Serait-il possible de préfixer ces classes en "GPtooltip" ou "gp-tooltip" comme c'est le cas pour toutes les autres classes, afin d'éviter ce conflit de nommage ?

Merci

**Comment by lowzonenose** [comment]
Effectivement, il y'a un petit oubli sur le  **préfixage** de cette classe CSS.
