### ISSUE TITLE
Extension OL3 : gestion des styles avec le format KML

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geoportal-extensions#98]
Dans le cadre des évolutions du portail, il est prévu de rendre éditable des croquis au format KML.
Pour l’édition du croquis, on utilise l'outil de dessin.

Mais, il nous faut revoir la manière de récupérer les styles suite à une lecture d'un KML dans l'outil de dessin avec l'utilisation de la fonction **feature.getStyleFunction()** (cf.http://openlayers.org/en/latest/apidoc/ol.html#.FeatureStyleFunction et http://openlayers.org/en/latest/apidoc/ol.Feature.html#getStyleFunction ) .

Selon la version d'openlayers, nous n'avons pas la même implémentation des styles dans le format KML. 

> Ex. entre la version 3.14 et 3.20, nous avons la).
 gestion des styles par défaut, les styles dits "partagés" (ex. styleUrl, styleMap), ainsi que d'autre fonctionnalités sur les styles / format KML...

Donc les modifications sur les styles concernent l'outil de dessin (**Drawing**), et éventuellement, l'outil d'import de données (**ImportLayer**).

_Liens (issues)_
https://github.com/openlayers/openlayers/issues/3262
https://github.com/openlayers/openlayers/issues/5981
https://github.com/openlayers/openlayers/issues/6028
https://github.com/openlayers/openlayers/issues/4461

_Notes_
> We used to store both Style and styleUrl on the feature properties. With this PR we no longer store the Style on the feature properties, because ol.style.Style objects are not JSON-serializable. But we still store styleUrl, probably just because we do not have any reason not to store it anymore.

**Comment by ajwittman** [comment]
If the style is no longer stored with the feature, then how do we access the KML style of a given feature?
